// Squad data for World Cup 2026 teams
// Based on historical data and projections. Will be updated as real squads are announced.

export interface Player {
  name: string;
  position: 'GK' | 'DEF' | 'MID' | 'FWD';
  number: number;
  club?: string;
  age?: number;
  caps?: number;
}

export interface Squad {
  teamCode: string;
  teamName: string;
  flag: string;
  group: string;
  formation: string;
  coach: string;
  players: Player[];
}

// Helper to generate a squad quickly
function s(
  teamCode: string, teamName: string, flag: string, group: string,
  formation: string, coach: string,
  players: [string, Player['position'], number, string?, number?, number?][],
): Squad {
  return {
    teamCode, teamName, flag, group, formation, coach,
    players: players.map(([name, position, number, club, age, caps]) => ({
      name, position, number, club, age, caps,
    })),
  };
}

const squads: Squad[] = [
  // ── Group A ──
  s('MEX', 'Mexico', '🇲🇽', 'A', '4-3-3', 'Javier Aguirre', [
    ['Guillermo Ochoa', 'GK', 13, 'Salernitana', 40, 150],
    ['Luis Malagon', 'GK', 1, 'Club América', 28, 8],
    ['Raul Rangel', 'GK', 12, 'Guadalajara', 25, 2],
    ['Cesar Montes', 'DEF', 3, 'Almeria', 28, 50],
    ['Johan Vasquez', 'DEF', 5, 'Genoa', 26, 30],
    ['Jesus Gallardo', 'DEF', 23, 'Monterrey', 30, 85],
    ['Jorge Sanchez', 'DEF', 2, 'Porto', 28, 45],
    ['Israel Reyes', 'DEF', 4, 'Club América', 25, 18],
    ['Edson Alvarez', 'MID', 18, 'West Ham', 28, 80],
    ['Luis Chavez', 'MID', 24, 'Dynamo Moscow', 29, 38],
    ['Orbelin Pineda', 'MID', 17, 'AEK Athens', 29, 65],
    ['Carlos Rodriguez', 'MID', 8, 'Cruz Azul', 28, 42],
    ['Erick Sanchez', 'MID', 14, 'Club América', 26, 22],
    ['Hirving Lozano', 'FWD', 22, 'PSV', 30, 75],
    ['Santiago Gimenez', 'FWD', 9, 'Feyenoord', 25, 35],
    ['Raul Jimenez', 'FWD', 10, 'Fulham', 35, 105],
    ['Julian Quiñones', 'FWD', 11, 'Club América', 29, 12],
    ['Alexis Vega', 'FWD', 19, 'Toluca', 28, 32],
    ['Uriel Antuna', 'FWD', 15, 'Cruz Azul', 28, 40],
  ]),
  s('RSA', 'South Africa', '🇿🇦', 'A', '4-4-2', 'Hugo Broos', [
    ['Ronwen Williams', 'GK', 1, 'Mamelodi Sundowns', 34, 45],
    ['Veli Mothwa', 'GK', 16, 'AmaZulu', 33, 10],
    ['Ricardo Goss', 'GK', 22, 'SuperSport United', 31, 3],
    ['Mothobi Mvala', 'DEF', 3, 'Mamelodi Sundowns', 31, 20],
    ['Grant Kekana', 'DEF', 5, 'Mamelodi Sundowns', 32, 15],
    ['Aubrey Modiba', 'DEF', 6, 'Mamelodi Sundowns', 29, 30],
    ['Nyiko Mobbie', 'DEF', 2, 'Sekhukhune United', 30, 22],
    ['Sibongiseni Mthethwa', 'DEF', 4, 'Kaizer Chiefs', 30, 12],
    ['Teboho Mokoena', 'MID', 8, 'Mamelodi Sundowns', 28, 35],
    ['Sphephelo Sithole', 'MID', 15, 'Tondela', 26, 18],
    ['Themba Zwane', 'MID', 10, 'Mamelodi Sundowns', 36, 42],
    ['Thapelo Morena', 'MID', 13, 'Mamelodi Sundowns', 31, 25],
    ['Oswin Appollis', 'FWD', 11, 'Polokwane City', 23, 8],
    ['Percy Tau', 'FWD', 7, 'Al Ahly', 32, 48],
    ['Lyle Foster', 'FWD', 9, 'Burnley', 25, 16],
    ['Bongokuhle Hlongwane', 'FWD', 19, 'Minnesota United', 26, 20],
    ['Evidence Makgopa', 'FWD', 21, 'Orlando Pirates', 25, 12],
  ]),
  s('KOR', 'South Korea', '🇰🇷', 'A', '4-4-2', 'Hong Myung-bo', [
    ['Kim Seung-gyu', 'GK', 1, 'Al-Shabab', 35, 80],
    ['Jo Hyeon-woo', 'GK', 21, 'Ulsan HD', 33, 30],
    ['Song Bum-keun', 'GK', 12, 'Shonan Bellmare', 28, 2],
    ['Kim Min-jae', 'DEF', 4, 'Bayern Munich', 29, 65],
    ['Kim Young-gwon', 'DEF', 19, 'Ulsan HD', 36, 110],
    ['Seol Young-woo', 'DEF', 22, 'Red Star', 27, 18],
    ['Lee Ki-je', 'DEF', 3, 'Suwon Samsung', 33, 12],
    ['Kim Tae-hwan', 'DEF', 23, 'Jeonbuk Hyundai', 35, 28],
    ['Son Heung-min', 'MID', 7, 'Tottenham', 33, 125],
    ['Lee Kang-in', 'MID', 18, 'PSG', 25, 35],
    ['Hwang In-beom', 'MID', 6, 'Red Star', 29, 60],
    ['Lee Jae-sung', 'MID', 10, 'Mainz', 32, 80],
    ['Paik Seung-ho', 'MID', 13, 'Birmingham City', 28, 22],
    ['Jeong Woo-yeong', 'MID', 17, 'Stuttgart', 26, 28],
    ['Hwang Hee-chan', 'FWD', 11, 'Wolves', 30, 68],
    ['Cho Gue-sung', 'FWD', 9, 'Midtjylland', 28, 38],
    ['Oh Hyeon-gyu', 'FWD', 20, 'Celtic', 25, 15],
  ]),

  // ── Group B ──
  s('CAN', 'Canada', '🇨🇦', 'B', '4-4-2', 'Jesse Marsch', [
    ['Maxime Crepeau', 'GK', 16, 'Portland Timbers', 32, 22],
    ['Dayne St. Clair', 'GK', 1, 'Minnesota United', 28, 8],
    ['Milan Borjan', 'GK', 18, 'Red Star', 38, 80],
    ['Alphonso Davies', 'DEF', 19, 'Bayern Munich', 25, 50],
    ['Alistair Johnston', 'DEF', 2, 'Celtic', 27, 45],
    ['Moise Bombito', 'DEF', 5, 'Nice', 25, 12],
    ['Derek Cornelius', 'DEF', 4, 'Malmo FF', 28, 25],
    ['Richie Laryea', 'DEF', 22, 'Toronto FC', 30, 52],
    ['Stephen Eustaquio', 'MID', 7, 'Porto', 28, 40],
    ['Ismael Kone', 'MID', 8, 'Marseille', 23, 25],
    ['Jonathan Osorio', 'MID', 21, 'Toronto FC', 33, 75],
    ['Samuel Piette', 'MID', 6, 'CF Montreal', 31, 70],
    ['Tajon Buchanan', 'MID', 17, 'Inter Milan', 26, 42],
    ['Cyle Larin', 'FWD', 9, 'Mallorca', 31, 72],
    ['Jonathan David', 'FWD', 20, 'Lille', 26, 52],
    ['Theo Bair', 'FWD', 11, 'Auxerre', 26, 6],
    ['Liam Millar', 'FWD', 15, 'Preston North End', 26, 32],
    ['Jacen Russell-Rowe', 'FWD', 23, 'Columbus Crew', 23, 4],
  ]),
  s('ARG', 'Argentina', '🇦🇷', 'B', '4-3-3', 'Lionel Scaloni', [
    ['Emiliano Martinez', 'GK', 23, 'Aston Villa', 33, 52],
    ['Gerónimo Rulli', 'GK', 12, 'Marseille', 32, 4],
    ['Walter Benitez', 'GK', 1, 'PSV', 32, 2],
    ['Cristian Romero', 'DEF', 13, 'Tottenham', 28, 40],
    ['Nicolas Otamendi', 'DEF', 19, 'Benfica', 38, 115],
    ['Lisandro Martinez', 'DEF', 25, 'Manchester United', 28, 25],
    ['Nahuel Molina', 'DEF', 26, 'Atletico Madrid', 28, 48],
    ['Marcos Acuña', 'DEF', 8, 'Sevilla', 34, 62],
    ['Gonzalo Montiel', 'DEF', 4, 'Sevilla', 29, 32],
    ['Rodrigo De Paul', 'MID', 7, 'Atletico Madrid', 32, 75],
    ['Enzo Fernandez', 'MID', 24, 'Chelsea', 25, 32],
    ['Alexis Mac Allister', 'MID', 20, 'Liverpool', 27, 38],
    ['Leandro Paredes', 'MID', 5, 'Roma', 31, 65],
    ['Giovani Lo Celso', 'MID', 16, 'Villarreal', 30, 52],
    ['Lionel Messi', 'FWD', 10, 'Inter Miami', 38, 188],
    ['Julian Alvarez', 'FWD', 9, 'Atletico Madrid', 26, 42],
    ['Lautaro Martinez', 'FWD', 22, 'Inter Milan', 28, 65],
    ['Alejandro Garnacho', 'FWD', 17, 'Manchester United', 22, 10],
    ['Nico Gonzalez', 'FWD', 15, 'Juventus', 27, 42],
  ]),

  // ── Group C ──
  s('USA', 'United States', '🇺🇸', 'C', '4-3-3', 'Mauricio Pochettino', [
    ['Matt Turner', 'GK', 1, 'Nottingham Forest', 32, 48],
    ['Ethan Horvath', 'GK', 18, 'Cardiff City', 31, 12],
    ['Gaga Slonina', 'GK', 25, 'Chelsea', 22, 2],
    ['Antonee Robinson', 'DEF', 5, 'Fulham', 28, 50],
    ['Sergino Dest', 'DEF', 2, 'PSV', 25, 38],
    ['Chris Richards', 'DEF', 15, 'Crystal Palace', 26, 28],
    ['Cameron Carter-Vickers', 'DEF', 3, 'Celtic', 28, 22],
    ['Tim Ream', 'DEF', 13, 'Charlotte FC', 38, 62],
    ['Weston McKennie', 'MID', 8, 'Juventus', 27, 58],
    ['Tyler Adams', 'MID', 4, 'Bournemouth', 27, 48],
    ['Gio Reyna', 'MID', 7, 'Nottingham Forest', 23, 32],
    ['Yunus Musah', 'MID', 6, 'AC Milan', 23, 42],
    ['Johnny Cardoso', 'MID', 12, 'Real Betis', 25, 18],
    ['Christian Pulisic', 'FWD', 10, 'AC Milan', 27, 78],
    ['Folarin Balogun', 'FWD', 9, 'Monaco', 25, 20],
    ['Ricardo Pepi', 'FWD', 21, 'PSV', 23, 30],
    ['Brenden Aaronson', 'FWD', 11, 'Leeds United', 25, 42],
    ['Tim Weah', 'FWD', 19, 'Juventus', 26, 42],
  ]),
  s('GER', 'Germany', '🇩🇪', 'C', '4-2-3-1', 'Julian Nagelsmann', [
    ['Marc-Andre ter Stegen', 'GK', 1, 'Barcelona', 34, 42],
    ['Oliver Baumann', 'GK', 12, 'Hoffenheim', 36, 0],
    ['Alexander Nubel', 'GK', 22, 'Stuttgart', 29, 2],
    ['Antonio Rudiger', 'DEF', 2, 'Real Madrid', 33, 78],
    ['Jonathan Tah', 'DEF', 4, 'Bayer Leverkusen', 30, 30],
    ['Nico Schlotterbeck', 'DEF', 15, 'Borussia Dortmund', 26, 18],
    ['David Raum', 'DEF', 3, 'RB Leipzig', 28, 28],
    ['Joshua Kimmich', 'DEF', 6, 'Bayern Munich', 31, 95],
    ['Robin Gosens', 'DEF', 20, 'Union Berlin', 31, 22],
    ['Pascal Gross', 'MID', 5, 'Borussia Dortmund', 34, 12],
    ['Aleksandar Pavlovic', 'MID', 25, 'Bayern Munich', 22, 4],
    ['Florian Wirtz', 'MID', 10, 'Bayer Leverkusen', 23, 28],
    ['Jamal Musiala', 'MID', 14, 'Bayern Munich', 23, 38],
    ['Leroy Sane', 'MID', 19, 'Bayern Munich', 30, 68],
    ['Kai Havertz', 'FWD', 7, 'Arsenal', 27, 52],
    ['Deniz Undav', 'FWD', 26, 'Stuttgart', 28, 8],
    ['Maximilian Beier', 'FWD', 9, 'Borussia Dortmund', 23, 4],
  ]),

  // ── Group D ──
  s('BRA', 'Brazil', '🇧🇷', 'D', '4-2-3-1', 'Dorival Junior', [
    ['Alisson', 'GK', 1, 'Liverpool', 33, 72],
    ['Ederson', 'GK', 23, 'Manchester City', 32, 28],
    ['Bento', 'GK', 12, 'Al-Nassr', 26, 2],
    ['Marquinhos', 'DEF', 4, 'PSG', 32, 90],
    ['Gabriel Magalhaes', 'DEF', 14, 'Arsenal', 27, 8],
    ['Eder Militao', 'DEF', 3, 'Real Madrid', 28, 38],
    ['Danilo', 'DEF', 2, 'Juventus', 34, 60],
    ['Guilherme Arana', 'DEF', 6, 'Atletico Mineiro', 28, 10],
    ['Vanderson', 'DEF', 13, 'Monaco', 24, 5],
    ['Bruno Guimaraes', 'MID', 8, 'Newcastle', 28, 30],
    ['Lucas Paqueta', 'MID', 10, 'West Ham', 28, 52],
    ['Joelinton', 'MID', 18, 'Newcastle', 29, 8],
    ['Vinicius Junior', 'FWD', 7, 'Real Madrid', 25, 38],
    ['Rodrygo', 'FWD', 11, 'Real Madrid', 25, 32],
    ['Raphinha', 'FWD', 19, 'Barcelona', 28, 32],
    ['Endrick', 'FWD', 9, 'Real Madrid', 20, 12],
    ['Gabriel Martinelli', 'FWD', 17, 'Arsenal', 25, 18],
    ['Savinho', 'FWD', 20, 'Manchester City', 22, 8],
  ]),
  s('JPN', 'Japan', '🇯🇵', 'D', '4-2-3-1', 'Hajime Moriyasu', [
    ['Zion Suzuki', 'GK', 23, 'Parma', 23, 15],
    ['Keisuke Osako', 'GK', 1, 'Sanfrecce Hiroshima', 27, 8],
    ['Daiya Maekawa', 'GK', 12, 'Vissel Kobe', 31, 2],
    ['Takehiro Tomiyasu', 'DEF', 16, 'Arsenal', 27, 45],
    ['Ko Itakura', 'DEF', 4, 'Borussia Mönchengladbach', 28, 35],
    ['Hiroki Ito', 'DEF', 22, 'Bayern Munich', 27, 22],
    ['Yuta Nakayama', 'DEF', 2, 'Huddersfield', 29, 28],
    ['Yukinari Sugawara', 'DEF', 3, 'Southampton', 25, 15],
    ['Wataru Endo', 'MID', 6, 'Liverpool', 32, 65],
    ['Hidemasa Morita', 'MID', 5, 'Sporting CP', 30, 38],
    ['Takefusa Kubo', 'MID', 15, 'Real Sociedad', 25, 42],
    ['Ritsu Doan', 'MID', 10, 'Freiburg', 28, 55],
    ['Kaoru Mitoma', 'MID', 7, 'Brighton', 28, 25],
    ['Daichi Kamada', 'MID', 17, 'Crystal Palace', 29, 38],
    ['Takumi Minamino', 'FWD', 11, 'Monaco', 31, 60],
    ['Ayase Ueda', 'FWD', 9, 'Feyenoord', 26, 30],
    ['Kyogo Furuhashi', 'FWD', 18, 'Celtic', 31, 22],
  ]),

  // ── Group E ──
  s('FRA', 'France', '🇫🇷', 'E', '4-3-3', 'Didier Deschamps', [
    ['Mike Maignan', 'GK', 16, 'AC Milan', 30, 28],
    ['Brice Samba', 'GK', 1, 'Lens', 32, 5],
    ['Lucas Chevalier', 'GK', 23, 'Lille', 23, 0],
    ['William Saliba', 'DEF', 17, 'Arsenal', 25, 30],
    ['Ibrahima Konate', 'DEF', 24, 'Liverpool', 27, 22],
    ['Dayot Upamecano', 'DEF', 2, 'Bayern Munich', 27, 28],
    ['Theo Hernandez', 'DEF', 22, 'AC Milan', 27, 38],
    ['Jules Kounde', 'DEF', 5, 'Barcelona', 27, 38],
    ['Ferland Mendy', 'DEF', 3, 'Real Madrid', 30, 14],
    ['Aurelien Tchouameni', 'MID', 8, 'Real Madrid', 26, 42],
    ['Eduardo Camavinga', 'MID', 6, 'Real Madrid', 23, 28],
    ['Warren Zaire-Emery', 'MID', 18, 'PSG', 20, 8],
    ['Adrien Rabiot', 'MID', 14, 'Marseille', 31, 52],
    ['Kylian Mbappe', 'FWD', 10, 'Real Madrid', 27, 88],
    ['Ousmane Dembele', 'FWD', 7, 'PSG', 28, 52],
    ['Bradley Barcola', 'FWD', 20, 'PSG', 23, 12],
    ['Marcus Thuram', 'FWD', 9, 'Inter Milan', 28, 28],
    ['Randal Kolo Muani', 'FWD', 12, 'PSG', 27, 25],
    ['Michael Olise', 'FWD', 21, 'Bayern Munich', 24, 5],
  ]),
  s('ENG', 'England', '🏴󠁧󠁢󠁥󠁮󠁧󠁿', 'E', '4-2-3-1', 'Thomas Tuchel', [
    ['Aaron Ramsdale', 'GK', 1, 'Southampton', 28, 8],
    ['Jordan Pickford', 'GK', 23, 'Everton', 32, 70],
    ['Dean Henderson', 'GK', 13, 'Crystal Palace', 29, 2],
    ['John Stones', 'DEF', 5, 'Manchester City', 32, 82],
    ['Marc Guehi', 'DEF', 6, 'Crystal Palace', 25, 22],
    ['Trent Alexander-Arnold', 'DEF', 2, 'Liverpool', 27, 32],
    ['Luke Shaw', 'DEF', 3, 'Manchester United', 30, 35],
    ['Levi Colwill', 'DEF', 15, 'Chelsea', 23, 8],
    ['Jude Bellingham', 'MID', 10, 'Real Madrid', 22, 40],
    ['Declan Rice', 'MID', 4, 'Arsenal', 27, 62],
    ['Conor Gallagher', 'MID', 16, 'Atletico Madrid', 26, 22],
    ['Cole Palmer', 'MID', 20, 'Chelsea', 24, 12],
    ['Phil Foden', 'MID', 11, 'Manchester City', 25, 42],
    ['Anthony Gordon', 'MID', 18, 'Newcastle', 25, 10],
    ['Harry Kane', 'FWD', 9, 'Bayern Munich', 32, 105],
    ['Bukayo Saka', 'FWD', 7, 'Arsenal', 24, 42],
    ['Ollie Watkins', 'FWD', 19, 'Aston Villa', 29, 18],
  ]),

  // ── Group F ──
  s('ESP', 'Spain', '🇪🇸', 'F', '4-3-3', 'Luis de la Fuente', [
    ['Unai Simon', 'GK', 23, 'Athletic Club', 29, 48],
    ['David Raya', 'GK', 1, 'Arsenal', 30, 12],
    ['Alex Remiro', 'GK', 13, 'Real Sociedad', 31, 2],
    ['Pau Cubarsi', 'DEF', 4, 'Barcelona', 19, 8],
    ['Aymeric Laporte', 'DEF', 3, 'Al-Nassr', 32, 38],
    ['Dani Vivian', 'DEF', 5, 'Athletic Club', 26, 10],
    ['Alejandro Grimaldo', 'DEF', 12, 'Bayer Leverkusen', 30, 12],
    ['Dani Carvajal', 'DEF', 2, 'Real Madrid', 34, 52],
    ['Pedri', 'MID', 8, 'Barcelona', 23, 28],
    ['Gavi', 'MID', 9, 'Barcelona', 22, 30],
    ['Fabian Ruiz', 'MID', 18, 'PSG', 30, 35],
    ['Martin Zubimendi', 'MID', 6, 'Real Sociedad', 27, 12],
    ['Alex Baena', 'MID', 21, 'Villarreal', 24, 8],
    ['Lamine Yamal', 'FWD', 19, 'Barcelona', 18, 22],
    ['Nico Williams', 'FWD', 17, 'Athletic Club', 23, 25],
    ['Alvaro Morata', 'FWD', 7, 'Atletico Madrid', 33, 80],
    ['Mikel Oyarzabal', 'FWD', 10, 'Real Sociedad', 29, 35],
    ['Ferrán Torres', 'FWD', 11, 'Barcelona', 26, 48],
  ]),
  s('MAR', 'Morocco', '🇲🇦', 'F', '4-3-3', 'Walid Regragui', [
    ['Yassine Bounou', 'GK', 1, 'Al-Hilal', 35, 68],
    ['Munir El Kajoui', 'GK', 12, 'Al-Wehda', 36, 45],
    ['El Mehdi Benabid', 'GK', 22, 'AS FAR', 28, 2],
    ['Achraf Hakimi', 'DEF', 2, 'PSG', 27, 80],
    ['Noussair Mazraoui', 'DEF', 3, 'Manchester United', 28, 32],
    ['Romain Saiss', 'DEF', 6, 'Al-Sadd', 36, 82],
    ['Nayef Aguerd', 'DEF', 5, 'West Ham', 30, 42],
    ['Chadi Riad', 'DEF', 13, 'Crystal Palace', 24, 8],
    ['Sofyan Amrabat', 'MID', 4, 'Fenerbahce', 29, 60],
    ['Azzedine Ounahi', 'MID', 8, 'Marseille', 26, 38],
    ['Amine Harit', 'MID', 7, 'Marseille', 28, 28],
    ['Brahim Diaz', 'MID', 10, 'Real Madrid', 26, 12],
    ['Bilal El Khannouss', 'MID', 15, 'Leicester City', 22, 18],
    ['Hakim Ziyech', 'FWD', 17, 'Galatasaray', 33, 62],
    ['Youssef En-Nesyri', 'FWD', 9, 'Fenerbahce', 28, 72],
    ['Soufiane Rahimi', 'FWD', 21, 'Al-Ain', 29, 18],
    ['Eliesse Ben Seghir', 'FWD', 11, 'Monaco', 21, 5],
    ['Ilias Akhomach', 'FWD', 19, 'Villarreal', 22, 8],
  ]),

  // ── Group G ──
  s('ITA', 'Italy', '🇮🇹', 'G', '4-3-3', 'Luciano Spalletti', [
    ['Gianluigi Donnarumma', 'GK', 1, 'PSG', 27, 72],
    ['Guglielmo Vicario', 'GK', 12, 'Tottenham', 29, 6],
    ['Marco Carnesecchi', 'GK', 26, 'Atalanta', 25, 2],
    ['Alessandro Bastoni', 'DEF', 23, 'Inter Milan', 27, 30],
    ['Alessandro Buongiorno', 'DEF', 4, 'Napoli', 26, 12],
    ['Giovanni Di Lorenzo', 'DEF', 2, 'Napoli', 32, 42],
    ['Federico Dimarco', 'DEF', 3, 'Inter Milan', 28, 28],
    ['Riccardo Calafiori', 'DEF', 5, 'Arsenal', 23, 8],
    ['Nicolo Barella', 'MID', 18, 'Inter Milan', 29, 58],
    ['Sandro Tonali', 'MID', 8, 'Newcastle', 26, 22],
    ['Davide Frattesi', 'MID', 16, 'Inter Milan', 26, 22],
    ['Lorenzo Pellegrini', 'MID', 7, 'Roma', 29, 35],
    ['Federico Chiesa', 'MID', 14, 'Liverpool', 28, 52],
    ['Mateo Retegui', 'FWD', 9, 'Atalanta', 27, 18],
    ['Giacomo Raspadori', 'FWD', 10, 'Napoli', 26, 32],
    ['Moise Kean', 'FWD', 11, 'Fiorentina', 26, 18],
    ['Nicolo Zaniolo', 'FWD', 22, 'Atalanta', 26, 22],
  ]),

  // ── Group H ──
  s('NED', 'Netherlands', '🇳🇱', 'H', '4-3-3', 'Ronald Koeman', [
    ['Bart Verbruggen', 'GK', 1, 'Brighton', 23, 18],
    ['Mark Flekken', 'GK', 13, 'Brentford', 32, 8],
    ['Nick Olij', 'GK', 23, 'Sparta Rotterdam', 29, 2],
    ['Virgil van Dijk', 'DEF', 4, 'Liverpool', 34, 78],
    ['Nathan Ake', 'DEF', 5, 'Manchester City', 31, 52],
    ['Matthijs de Ligt', 'DEF', 3, 'Manchester United', 26, 48],
    ['Denzel Dumfries', 'DEF', 22, 'Inter Milan', 29, 60],
    ['Lutsharel Geertruida', 'DEF', 2, 'RB Leipzig', 25, 15],
    ['Frenkie de Jong', 'MID', 21, 'Barcelona', 28, 58],
    ['Ryan Gravenberch', 'MID', 8, 'Liverpool', 24, 15],
    ['Tijjani Reijnders', 'MID', 14, 'AC Milan', 26, 18],
    ['Teun Koopmeiners', 'MID', 20, 'Juventus', 28, 25],
    ['Xavi Simons', 'MID', 10, 'RB Leipzig', 23, 28],
    ['Cody Gakpo', 'FWD', 11, 'Liverpool', 27, 35],
    ['Memphis Depay', 'FWD', 9, 'Corinthians', 32, 98],
    ['Brian Brobbey', 'FWD', 19, 'Ajax', 24, 8],
    ['Donyell Malen', 'FWD', 18, 'Borussia Dortmund', 27, 38],
  ]),
  s('CRO', 'Croatia', '🇭🇷', 'H', '4-3-3', 'Zlatko Dalic', [
    ['Dominik Livakovic', 'GK', 1, 'Fenerbahce', 31, 58],
    ['Ivica Ivusic', 'GK', 12, 'Pafos', 31, 8],
    ['Nediljko Labrovic', 'GK', 23, 'Augsburg', 26, 2],
    ['Josko Gvardiol', 'DEF', 4, 'Manchester City', 24, 38],
    ['Josip Sutalo', 'DEF', 6, 'Ajax', 26, 22],
    ['Josip Stanisic', 'DEF', 2, 'Bayern Munich', 26, 22],
    ['Borna Sosa', 'DEF', 19, 'Ajax', 28, 25],
    ['Marin Pongracic', 'DEF', 5, 'Fiorentina', 28, 12],
    ['Luka Modric', 'MID', 10, 'Real Madrid', 40, 185],
    ['Mateo Kovacic', 'MID', 8, 'Manchester City', 32, 108],
    ['Marcelo Brozovic', 'MID', 11, 'Al-Nassr', 33, 98],
    ['Mario Pasalic', 'MID', 15, 'Atalanta', 31, 72],
    ['Lovro Majer', 'MID', 7, 'Wolfsburg', 28, 32],
    ['Luka Sucic', 'MID', 25, 'Real Sociedad', 23, 12],
    ['Andrej Kramaric', 'FWD', 9, 'Hoffenheim', 35, 98],
    ['Ante Budimir', 'FWD', 17, 'Osasuna', 35, 25],
    ['Ivan Perisic', 'FWD', 14, 'Hajduk Split', 37, 135],
  ]),

  // ── Remaining teams (condensed but realistic) ──
  s('SEN', 'Senegal', '🇸🇳', 'I', '4-3-3', 'Pape Thiaw', [
    ['Edouard Mendy', 'GK', 16, 'Al-Ahli', 33, 42],
    ['Seny Dieng', 'GK', 1, 'Middlesbrough', 31, 8],
    ['Kalidou Koulibaly', 'DEF', 3, 'Al-Hilal', 35, 85],
    ['Abdou Diallo', 'DEF', 22, 'Al-Arabi', 29, 35],
    ['Ismail Jakobs', 'DEF', 2, 'Galatasaray', 27, 22],
    ['Moussa Niakhate', 'DEF', 4, 'Lyon', 29, 15],
    ['Idrissa Gueye', 'MID', 5, 'Everton', 36, 110],
    ['Pape Matar Sarr', 'MID', 17, 'Tottenham', 23, 28],
    ['Lamine Camara', 'MID', 6, 'Monaco', 22, 22],
    ['Sadio Mane', 'FWD', 10, 'Al-Nassr', 34, 108],
    ['Nicolas Jackson', 'FWD', 7, 'Chelsea', 25, 18],
    ['Ismaila Sarr', 'FWD', 18, 'Marseille', 28, 65],
    ['Boulaye Dia', 'FWD', 9, 'Lazio', 29, 35],
    ['Habib Diallo', 'FWD', 20, 'Damac', 30, 22],
  ]),
  s('COL', 'Colombia', '🇨🇴', 'I', '4-2-3-1', 'Nestor Lorenzo', [
    ['Camilo Vargas', 'GK', 12, 'Atlas', 37, 28],
    ['David Ospina', 'GK', 1, 'Al-Nassr', 37, 128],
    ['Davinson Sanchez', 'DEF', 23, 'Galatasaray', 29, 65],
    ['Yerry Mina', 'DEF', 2, 'Cagliari', 31, 48],
    ['Daniel Munoz', 'DEF', 21, 'Crystal Palace', 28, 30],
    ['Johan Mojica', 'DEF', 17, 'Osasuna', 33, 35],
    ['Jefferson Lerma', 'MID', 16, 'Crystal Palace', 31, 48],
    ['James Rodriguez', 'MID', 10, 'Sao Paulo', 35, 108],
    ['Juan Fernando Quintero', 'MID', 20, 'Racing Club', 33, 42],
    ['Luis Diaz', 'FWD', 7, 'Liverpool', 28, 58],
    ['Jhon Duran', 'FWD', 9, 'Al-Nassr', 24, 15],
    ['Rafael Santos Borre', 'FWD', 19, 'Internacional', 30, 35],
    ['Jhon Arias', 'FWD', 11, 'Fluminense', 28, 22],
    ['Luis Sinisterra', 'FWD', 14, 'Bournemouth', 26, 18],
  ]),
  s('URU', 'Uruguay', '🇺🇾', 'J', '4-3-3', 'Marcelo Bielsa', [
    ['Sergio Rochet', 'GK', 1, 'Internacional', 33, 25],
    ['Franco Israel', 'GK', 12, 'Sporting CP', 26, 4],
    ['Ronald Araujo', 'DEF', 4, 'Barcelona', 27, 22],
    ['Jose Gimenez', 'DEF', 2, 'Atletico Madrid', 31, 90],
    ['Mathias Olivera', 'DEF', 16, 'Napoli', 28, 25],
    ['Sebastian Caceres', 'DEF', 3, 'Club América', 27, 15],
    ['Federico Valverde', 'MID', 15, 'Real Madrid', 27, 65],
    ['Manuel Ugarte', 'MID', 5, 'Manchester United', 25, 28],
    ['Rodrigo Bentancur', 'MID', 6, 'Tottenham', 28, 65],
    ['Nicolas De La Cruz', 'MID', 7, 'Flamengo', 29, 30],
    ['Darwin Nunez', 'FWD', 9, 'Liverpool', 27, 32],
    ['Federico Pellistri', 'FWD', 11, 'Panathinaikos', 24, 28],
    ['Maximiliano Araujo', 'FWD', 13, 'Toluca', 26, 15],
    ['Cristian Olivera', 'FWD', 17, 'Los Angeles FC', 24, 10],
  ]),
  s('POR', 'Portugal', '🇵🇹', 'J', '4-3-3', 'Roberto Martinez', [
    ['Diogo Costa', 'GK', 22, 'Porto', 26, 35],
    ['Rui Patricio', 'GK', 1, 'Atalanta', 38, 112],
    ['Ruben Dias', 'DEF', 3, 'Manchester City', 29, 62],
    ['Goncalo Inacio', 'DEF', 14, 'Sporting CP', 24, 15],
    ['Nuno Mendes', 'DEF', 19, 'PSG', 24, 30],
    ['Diogo Dalot', 'DEF', 2, 'Manchester United', 27, 28],
    ['Joao Cancelo', 'DEF', 20, 'Al-Hilal', 32, 58],
    ['Bruno Fernandes', 'MID', 8, 'Manchester United', 31, 75],
    ['Vitinha', 'MID', 23, 'PSG', 26, 25],
    ['Joao Palhinha', 'MID', 6, 'Bayern Munich', 29, 35],
    ['Joao Neves', 'MID', 21, 'PSG', 21, 12],
    ['Cristiano Ronaldo', 'FWD', 7, 'Al-Nassr', 41, 215],
    ['Rafael Leao', 'FWD', 17, 'AC Milan', 27, 38],
    ['Diogo Jota', 'FWD', 9, 'Liverpool', 29, 42],
    ['Goncalo Ramos', 'FWD', 26, 'PSG', 25, 18],
    ['Pedro Neto', 'FWD', 11, 'Chelsea', 26, 15],
  ]),
  s('BEL', 'Belgium', '🇧🇪', 'K', '4-2-3-1', 'Domenico Tedesco', [
    ['Koen Casteels', 'GK', 1, 'Al-Qadsiah', 33, 12],
    ['Matz Sels', 'GK', 13, 'Nottingham Forest', 34, 8],
    ['Wout Faes', 'DEF', 4, 'Leicester City', 28, 22],
    ['Zeno Debast', 'DEF', 2, 'Sporting CP', 21, 12],
    ['Thomas Meunier', 'DEF', 15, 'Lille', 34, 72],
    ['Arthur Theate', 'DEF', 5, 'Al-Ittihad', 26, 18],
    ['Amadou Onana', 'MID', 6, 'Aston Villa', 24, 22],
    ['Youri Tielemans', 'MID', 8, 'Aston Villa', 29, 72],
    ['Charles De Ketelaere', 'MID', 17, 'Atalanta', 25, 22],
    ['Kevin De Bruyne', 'MID', 7, 'Manchester City', 35, 108],
    ['Jeremy Doku', 'FWD', 11, 'Manchester City', 23, 28],
    ['Leandro Trossard', 'FWD', 10, 'Arsenal', 31, 38],
    ['Romelu Lukaku', 'FWD', 9, 'Napoli', 33, 120],
    ['Lois Openda', 'FWD', 19, 'RB Leipzig', 26, 22],
    ['Johan Bakayoko', 'FWD', 21, 'PSV', 23, 15],
  ]),

  // ── More teams (abbreviated) ──
  s('NGA', 'Nigeria', '🇳🇬', 'K', '4-4-2', 'Eric Chelle', [
    ['Stanley Nwabali', 'GK', 1, 'Chippa United', 28, 10],
    ['Francis Uzoho', 'GK', 23, 'Omonia', 26, 35],
    ['Calvin Bassey', 'DEF', 3, 'Fulham', 26, 25],
    ['Ola Aina', 'DEF', 2, 'Nottingham Forest', 29, 42],
    ['Semi Ajayi', 'DEF', 6, 'West Brom', 31, 38],
    ['Bright Osayi-Samuel', 'DEF', 12, 'Fenerbahce', 28, 18],
    ['Wilfred Ndidi', 'MID', 4, 'Leicester City', 29, 58],
    ['Alex Iwobi', 'MID', 8, 'Fulham', 29, 80],
    ['Frank Onyeka', 'MID', 15, 'Brentford', 28, 30],
    ['Victor Osimhen', 'FWD', 9, 'Galatasaray', 27, 38],
    ['Ademola Lookman', 'FWD', 11, 'Atalanta', 27, 28],
    ['Samuel Chukwueze', 'FWD', 13, 'AC Milan', 26, 38],
    ['Victor Boniface', 'FWD', 19, 'Bayer Leverkusen', 25, 12],
    ['Kelechi Iheanacho', 'FWD', 14, 'Sevilla', 29, 55],
  ]),
  s('EGY', 'Egypt', '🇪🇬', 'L', '4-3-3', 'Hossam Hassan', [
    ['Mohamed El Shenawy', 'GK', 1, 'Al-Ahly', 37, 58],
    ['Ahmed Hegazi', 'DEF', 6, 'Al-Ittihad', 34, 85],
    ['Mohamed Abdelmonem', 'DEF', 2, 'Nice', 26, 30],
    ['Mohamed Hany', 'DEF', 3, 'Al-Ahly', 29, 25],
    ['Mohamed Elneny', 'MID', 5, 'Al-Jazira', 33, 98],
    ['Emam Ashour', 'MID', 8, 'Al-Ahly', 27, 22],
    ['Hamdi Fathi', 'MID', 14, 'Al-Wakrah', 30, 25],
    ['Mohamed Salah', 'FWD', 10, 'Liverpool', 33, 102],
    ['Mostafa Mohamed', 'FWD', 9, 'Nantes', 27, 42],
    ['Omar Marmoush', 'FWD', 7, 'Manchester City', 27, 35],
    ['Trezeguet', 'FWD', 22, 'Trabzonspor', 31, 78],
    ['Ahmed Sayed Zizo', 'FWD', 11, 'Zamalek', 29, 38],
  ]),
  s('QAT', 'Qatar', '🇶🇦', 'L', '4-4-2', 'Tintin Marquez', [
    ['Meshaal Barsham', 'GK', 1, 'Al-Sadd', 28, 38],
    ['Boualem Khoukhi', 'DEF', 16, 'Al-Sadd', 35, 110],
    ['Pedro Miguel', 'DEF', 15, 'Al-Sadd', 34, 98],
    ['Tarek Salman', 'DEF', 5, 'Al-Sadd', 28, 78],
    ['Homam Ahmed', 'DEF', 14, 'Al-Duhail', 27, 55],
    ['Abdulaziz Hatem', 'MID', 6, 'Al-Rayyan', 35, 115],
    ['Hassan Al-Haydos', 'MID', 10, 'Al-Sadd', 35, 180],
    ['Jassem Gaber', 'MID', 23, 'Al-Arabi', 24, 28],
    ['Akram Afif', 'FWD', 11, 'Al-Sadd', 29, 112],
    ['Almoez Ali', 'FWD', 19, 'Al-Duhail', 29, 115],
    ['Yusuf Abdurisag', 'FWD', 9, 'Al-Sadd', 26, 35],
    ['Ahmed Alaaeldin', 'FWD', 7, 'Al-Duhail', 33, 62],
  ]),
  s('KSA', 'Saudi Arabia', '🇸🇦', 'M', '4-3-3', 'Roberto Mancini', [
    ['Mohammed Al-Owais', 'GK', 21, 'Al-Hilal', 34, 48],
    ['Yasser Al-Shahrani', 'DEF', 13, 'Al-Hilal', 33, 78],
    ['Ali Al-Bulaihi', 'DEF', 5, 'Al-Hilal', 36, 52],
    ['Hassan Tambakti', 'DEF', 17, 'Al-Hilal', 27, 35],
    ['Saud Abdulhamid', 'DEF', 2, 'Roma', 26, 38],
    ['Abdulelah Al-Malki', 'MID', 8, 'Al-Hilal', 31, 35],
    ['Salem Al-Dawsari', 'MID', 10, 'Al-Hilal', 34, 85],
    ['Mohamed Kanno', 'MID', 28, 'Al-Hilal', 31, 55],
    ['Salman Al-Faraj', 'MID', 7, 'Al-Hilal', 36, 78],
    ['Firas Al-Buraikan', 'FWD', 9, 'Al-Ahli', 26, 42],
    ['Saleh Al-Shehri', 'FWD', 11, 'Al-Hilal', 31, 38],
    ['Abdullah Radif', 'FWD', 20, 'Al-Hilal', 22, 10],
  ]),
  s('AUS', 'Australia', '🇦🇺', 'M', '4-4-2', 'Tony Popovic', [
    ['Mathew Ryan', 'GK', 1, 'Roma', 34, 95],
    ['Joe Gauci', 'GK', 12, 'Aston Villa', 25, 6],
    ['Harry Souttar', 'DEF', 19, 'Leicester City', 27, 32],
    ['Kye Rowles', 'DEF', 4, 'Hearts', 28, 22],
    ['Cameron Burgess', 'DEF', 5, 'Ipswich Town', 29, 12],
    ['Aziz Behich', 'DEF', 16, 'Melbourne City', 34, 68],
    ['Jackson Irvine', 'MID', 22, 'St. Pauli', 33, 72],
    ['Ajdin Hrustic', 'MID', 10, 'Salernitana', 29, 28],
    ['Riley McGree', 'MID', 14, 'Middlesbrough', 26, 25],
    ['Awer Mabil', 'MID', 11, 'Grasshoppers', 30, 35],
    ['Nestory Irankunda', 'FWD', 20, 'Bayern Munich', 20, 5],
    ['Kusini Yengi', 'FWD', 9, 'Portsmouth', 26, 10],
    ['Mitchell Duke', 'FWD', 15, 'Machida Zelvia', 35, 42],
  ]),
  s('IRN', 'Iran', '🇮🇷', 'N', '4-4-2', 'Amir Ghalenoei', [
    ['Alireza Beiranvand', 'GK', 1, 'Persepolis', 33, 72],
    ['Shoja Khalilzadeh', 'DEF', 4, 'Tractor', 37, 42],
    ['Hossein Kanani', 'DEF', 13, 'Persepolis', 32, 55],
    ['Ehsan Hajsafi', 'DEF', 3, 'AEK Athens', 36, 138],
    ['Ramin Rezaeian', 'DEF', 23, 'Sepahan', 36, 65],
    ['Saeid Ezatolahi', 'MID', 6, 'Shabab Al-Ahli', 29, 72],
    ['Saman Ghoddos', 'MID', 17, 'Al-Ittihad Kalba', 32, 55],
    ['Alireza Jahanbakhsh', 'MID', 7, 'Feyenoord', 33, 85],
    ['Mehdi Taremi', 'FWD', 9, 'Inter Milan', 33, 85],
    ['Sardar Azmoun', 'FWD', 20, 'Shabab Al-Ahli', 31, 82],
    ['Mehdi Ghayedi', 'FWD', 11, 'Al-Ittihad Kalba', 27, 28],
    ['Allahyar Sayyadmanesh', 'FWD', 15, 'Westerlo', 25, 18],
  ]),
  s('SWE', 'Sweden', '🇸🇪', 'N', '4-4-2', 'Jon Dahl Tomasson', [
    ['Robin Olsen', 'GK', 1, 'Aston Villa', 36, 75],
    ['Victor Lindelof', 'DEF', 3, 'Manchester United', 31, 70],
    ['Isak Hien', 'DEF', 4, 'Atalanta', 27, 15],
    ['Ludwig Augustinsson', 'DEF', 6, 'Anderlecht', 32, 58],
    ['Emil Holm', 'DEF', 2, 'Atalanta', 25, 12],
    ['Jens Cajuste', 'MID', 8, 'Ipswich Town', 27, 22],
    ['Mattias Svanberg', 'MID', 7, 'Wolfsburg', 27, 38],
    ['Emil Forsberg', 'MID', 10, 'New York Red Bulls', 34, 88],
    ['Alexander Isak', 'FWD', 9, 'Newcastle', 26, 50],
    ['Viktor Gyokeres', 'FWD', 17, 'Sporting CP', 28, 28],
    ['Dejan Kulusevski', 'FWD', 21, 'Tottenham', 26, 42],
    ['Anthony Elanga', 'FWD', 19, 'Nottingham Forest', 24, 18],
  ]),
  s('DEN', 'Denmark', '🇩🇰', 'O', '4-3-3', 'Kasper Hjulmand', [
    ['Kasper Schmeichel', 'GK', 1, 'Celtic', 39, 105],
    ['Mads Hermansen', 'GK', 16, 'Leicester City', 25, 2],
    ['Andreas Christensen', 'DEF', 6, 'Barcelona', 29, 75],
    ['Joachim Andersen', 'DEF', 2, 'Fulham', 29, 35],
    ['Victor Kristiansen', 'DEF', 5, 'Leicester City', 23, 15],
    ['Joakim Maehle', 'DEF', 18, 'Wolfsburg', 28, 48],
    ['Pierre-Emile Hojbjerg', 'MID', 23, 'Marseille', 30, 78],
    ['Christian Eriksen', 'MID', 10, 'Manchester United', 34, 135],
    ['Morten Hjulmand', 'MID', 21, 'Sporting CP', 26, 12],
    ['Rasmus Hojlund', 'FWD', 9, 'Manchester United', 23, 22],
    ['Andreas Skov Olsen', 'FWD', 11, 'Wolfsburg', 26, 32],
    ['Jonas Wind', 'FWD', 19, 'Wolfsburg', 27, 30],
    ['Mikkel Damsgaard', 'FWD', 14, 'Brentford', 25, 30],
  ]),

  // Placeholder for remaining 48 teams not yet listed
  s('PAN', 'Panama', '🇵🇦', 'A', '4-4-2', 'Thomas Christiansen', [
    ['Luis Mejia', 'GK', 1, 'Nacional', 35, 52],
    ['Fidel Escobar', 'DEF', 4, 'Saprissa', 31, 78],
    ['Michael Murillo', 'DEF', 23, 'Marseille', 29, 72],
    ['Adalberto Carrasquilla', 'MID', 8, 'Houston Dynamo', 28, 58],
    ['Anibal Godoy', 'MID', 20, 'Nashville SC', 36, 138],
    ['Edgar Barcenas', 'MID', 10, 'Mazatlan', 31, 88],
    ['Jose Fajardo', 'FWD', 9, 'Independiente', 31, 52],
    ['Ismael Diaz', 'FWD', 7, 'Universidad Catolica', 29, 42],
    ['Cecilio Waterman', 'FWD', 18, 'Coquimbo Unido', 33, 35],
    ['Jose Luis Rodriguez', 'FWD', 17, 'Red Star', 28, 45],
  ]),
  s('NZL', 'New Zealand', '🇳🇿', 'B', '4-4-2', 'Darren Bazeley', [
    ['Oli Sail', 'GK', 1, 'Perth Glory', 30, 28],
    ['Michael Boxall', 'DEF', 5, 'Minnesota United', 37, 48],
    ['Nando Pijnaker', 'DEF', 2, 'Sligo Rovers', 27, 18],
    ['Liberato Cacace', 'DEF', 3, 'Empoli', 26, 22],
    ['Sarpreet Singh', 'MID', 10, 'Hansa Rostock', 27, 15],
    ['Joe Bell', 'MID', 8, 'Viking', 27, 18],
    ['Marko Stamenic', 'MID', 6, 'Olympiacos', 24, 22],
    ['Chris Wood', 'FWD', 9, 'Nottingham Forest', 34, 78],
    ['Ben Waine', 'FWD', 11, 'Plymouth Argyle', 25, 15],
    ['Callum McCowatt', 'FWD', 7, 'Silkeborg', 27, 18],
  ]),
  s('CHI', 'Chile', '🇨🇱', 'G', '4-4-2', 'Ricardo Gareca', [
    ['Brayan Cortes', 'GK', 12, 'Colo-Colo', 31, 18],
    ['Gabriel Arias', 'GK', 1, 'Racing Club', 38, 15],
    ['Paulo Diaz', 'DEF', 5, 'River Plate', 31, 48],
    ['Guillermo Maripan', 'DEF', 3, 'Torino', 32, 48],
    ['Mauricio Isla', 'DEF', 4, 'Colo-Colo', 38, 142],
    ['Gabriel Suazo', 'DEF', 2, 'Toulouse', 28, 28],
    ['Arturo Vidal', 'MID', 8, 'Colo-Colo', 39, 148],
    ['Erick Pulgar', 'MID', 13, 'Flamengo', 32, 52],
    ['Vicente Pizarro', 'MID', 14, 'Colo-Colo', 23, 12],
    ['Alexis Sanchez', 'FWD', 7, 'Udinese', 37, 165],
    ['Ben Brereton Diaz', 'FWD', 22, 'Southampton', 27, 32],
    ['Dario Osorio', 'FWD', 11, 'Midtjylland', 22, 10],
    ['Alexander Aravena', 'FWD', 19, 'Gremio', 23, 5],
  ]),
  s('CIV', 'Ivory Coast', '🇨🇮', 'I', '4-3-3', 'Emerse Fae', [
    ['Yahia Fofana', 'GK', 1, 'Angers', 25, 15],
    ['Serge Aurier', 'DEF', 17, 'Galatasaray', 33, 92],
    ['Evan Ndicka', 'DEF', 3, 'Roma', 26, 18],
    ['Ousmane Diomande', 'DEF', 5, 'Sporting CP', 22, 8],
    ['Willy Boly', 'DEF', 6, 'Nottingham Forest', 35, 22],
    ['Franck Kessie', 'MID', 8, 'Al-Ahli', 29, 78],
    ['Seko Fofana', 'MID', 4, 'Al-Ettifaq', 31, 22],
    ['Ibrahim Sangare', 'MID', 18, 'Nottingham Forest', 28, 42],
    ['Simon Adingra', 'MID', 11, 'Brighton', 24, 15],
    ['Nicolas Pepe', 'FWD', 9, 'Villarreal', 31, 42],
    ['Sebastien Haller', 'FWD', 22, 'Leganes', 32, 28],
    ['Oumar Diakite', 'FWD', 19, 'Reims', 22, 8],
  ]),
  s('NOR', 'Norway', '🇳🇴', 'D', '4-3-3', 'Stale Solbakken', [
    ['Orjan Nyland', 'GK', 1, 'Sevilla', 35, 58],
    ['Leo Ostigard', 'DEF', 4, 'Rennes', 26, 25],
    ['Julian Ryerson', 'DEF', 14, 'Borussia Dortmund', 27, 25],
    ['Kristoffer Ajer', 'DEF', 3, 'Brentford', 28, 38],
    ['David Moller Wolfe', 'DEF', 19, 'AZ Alkmaar', 25, 8],
    ['Martin Odegaard', 'MID', 10, 'Arsenal', 27, 62],
    ['Sander Berge', 'MID', 8, 'Burnley', 28, 48],
    ['Oscar Bobb', 'MID', 20, 'Manchester City', 23, 10],
    ['Erling Haaland', 'FWD', 9, 'Manchester City', 25, 38],
    ['Alexander Sorloth', 'FWD', 23, 'Atletico Madrid', 30, 55],
    ['Antonio Nusa', 'FWD', 11, 'RB Leipzig', 21, 12],
    ['Jorgen Strand Larsen', 'FWD', 7, 'Wolves', 26, 18],
  ]),
  s('SUI', 'Switzerland', '🇨🇭', 'F', '4-2-3-1', 'Murat Yakin', [
    ['Gregor Kobel', 'GK', 1, 'Borussia Dortmund', 28, 8],
    ['Yann Sommer', 'GK', 21, 'Inter Milan', 37, 92],
    ['Manuel Akanji', 'DEF', 5, 'Manchester City', 30, 65],
    ['Nico Elvedi', 'DEF', 4, 'Borussia Mönchengladbach', 29, 58],
    ['Ricardo Rodriguez', 'DEF', 13, 'Real Betis', 33, 118],
    ['Silvan Widmer', 'DEF', 3, 'Mainz', 32, 48],
    ['Remo Freuler', 'MID', 8, 'Bologna', 34, 72],
    ['Granit Xhaka', 'MID', 10, 'Bayer Leverkusen', 33, 128],
    ['Denis Zakaria', 'MID', 6, 'Monaco', 28, 55],
    ['Ruben Vargas', 'MID', 7, 'Sevilla', 27, 48],
    ['Breel Embolo', 'FWD', 9, 'Monaco', 29, 68],
    ['Zeki Amdouni', 'FWD', 19, 'Benfica', 25, 22],
    ['Dan Ndoye', 'FWD', 17, 'Bologna', 25, 18],
  ]),
  s('AUT', 'Austria', '🇦🇹', 'E', '4-4-2', 'Ralf Rangnick', [
    ['Heinz Lindner', 'GK', 1, 'Union Saint-Gilloise', 35, 42],
    ['Patrick Pentz', 'GK', 13, 'FC Copenhagen', 29, 12],
    ['David Alaba', 'DEF', 8, 'Real Madrid', 33, 108],
    ['Kevin Danso', 'DEF', 4, 'Tottenham', 27, 25],
    ['Philipp Lienhart', 'DEF', 15, 'Freiburg', 29, 28],
    ['Stefan Posch', 'DEF', 5, 'Bologna', 28, 38],
    ['Konrad Laimer', 'MID', 20, 'Bayern Munich', 28, 42],
    ['Marcel Sabitzer', 'MID', 9, 'Borussia Dortmund', 32, 82],
    ['Christoph Baumgartner', 'MID', 19, 'RB Leipzig', 26, 42],
    ['Nicolas Seiwald', 'MID', 6, 'RB Leipzig', 24, 30],
    ['Marko Arnautovic', 'FWD', 7, 'Inter Milan', 37, 118],
    ['Michael Gregoritsch', 'FWD', 11, 'Freiburg', 32, 58],
    ['Junior Adamu', 'FWD', 14, 'Freiburg', 24, 8],
  ]),
  s('PER', 'Peru', '🇵🇪', 'G', '4-2-3-1', 'Jorge Fossati', [
    ['Pedro Gallese', 'GK', 1, 'Orlando City', 36, 108],
    ['Carlos Caceda', 'GK', 12, 'Melgar', 33, 8],
    ['Alexander Callens', 'DEF', 22, 'AEK Athens', 34, 42],
    ['Carlos Zambrano', 'DEF', 5, 'Alianza Lima', 36, 78],
    ['Luis Advincula', 'DEF', 17, 'Boca Juniors', 36, 118],
    ['Miguel Trauco', 'DEF', 6, 'San Jose Earthquakes', 32, 72],
    ['Renato Tapia', 'MID', 13, 'Celta Vigo', 30, 85],
    ['Pedro Aquino', 'MID', 23, 'Santos Laguna', 31, 42],
    ['Christian Cueva', 'MID', 8, 'Cienciano', 34, 100],
    ['Gianluca Lapadula', 'FWD', 9, 'Cagliari', 36, 30],
    ['Bryan Reyna', 'FWD', 14, 'Belgrano', 27, 12],
    ['Franco Zanelatto', 'FWD', 7, 'Alianza Lima', 26, 8],
  ]),
  s('ECU', 'Ecuador', '🇪🇨', 'J', '4-4-2', 'Sebastian Beccacece', [
    ['Alexander Dominguez', 'GK', 22, 'LDU Quito', 39, 78],
    ['Hernan Galindez', 'GK', 1, 'Huracan', 38, 22],
    ['Piero Hincapie', 'DEF', 3, 'Bayer Leverkusen', 24, 38],
    ['Felix Torres', 'DEF', 2, 'Corinthians', 29, 38],
    ['Angelo Preciado', 'DEF', 17, 'Sparta Prague', 27, 42],
    ['Pervis Estupinan', 'DEF', 7, 'Brighton', 28, 40],
    ['Moises Caicedo', 'MID', 23, 'Chelsea', 25, 48],
    ['Carlos Gruezo', 'MID', 20, 'San Jose Earthquakes', 31, 58],
    ['Alan Franco', 'MID', 21, 'Atletico Mineiro', 27, 35],
    ['Jeremy Sarmiento', 'MID', 10, 'Burnley', 23, 18],
    ['Enner Valencia', 'FWD', 13, 'Internacional', 36, 88],
    ['Kevin Rodriguez', 'FWD', 11, 'Union Saint-Gilloise', 26, 15],
    ['Kendry Paez', 'FWD', 16, 'Chelsea', 19, 5],
  ]),
  s('PAR', 'Paraguay', '🇵🇾', 'K', '4-4-2', 'Gustavo Alfaro', [
    ['Carlos Coronel', 'GK', 1, 'New York Red Bulls', 29, 12],
    ['Gustavo Gomez', 'DEF', 15, 'Palmeiras', 33, 78],
    ['Fabian Balbuena', 'DEF', 5, 'Dinamo Moscow', 34, 48],
    ['Robert Rojas', 'DEF', 2, 'River Plate', 30, 28],
    ['Mathias Villasanti', 'MID', 23, 'Gremio', 28, 42],
    ['Diego Gomez', 'MID', 8, 'Inter Miami', 23, 12],
    ['Andres Cubas', 'MID', 14, 'Vancouver Whitecaps', 30, 22],
    ['Miguel Almiron', 'MID', 10, 'Newcastle', 32, 62],
    ['Julio Enciso', 'FWD', 11, 'Brighton', 22, 18],
    ['Ramon Sosa', 'FWD', 19, 'Nottingham Forest', 26, 15],
    ['Antonio Sanabria', 'FWD', 9, 'Torino', 29, 32],
    ['Angel Romero', 'FWD', 7, 'Corinthians', 33, 45],
  ]),
  s('VEN', 'Venezuela', '🇻🇪', 'L', '4-4-2', 'Fernando Batista', [
    ['Rafael Romo', 'GK', 1, 'Universidad Catolica', 36, 22],
    ['Yordan Osorio', 'DEF', 4, 'Parma', 32, 32],
    ['Nahuel Ferraresi', 'DEF', 3, 'Sao Paulo', 28, 28],
    ['Jon Aramburu', 'DEF', 2, 'Real Sociedad', 23, 8],
    ['Tomas Rincon', 'MID', 8, 'Santos', 38, 138],
    ['Yangel Herrera', 'MID', 6, 'Girona', 28, 38],
    ['Jose Martinez', 'MID', 13, 'Philadelphia Union', 31, 32],
    ['Jefferson Savarino', 'MID', 10, 'Real Salt Lake', 29, 42],
    ['Salomon Rondon', 'FWD', 23, 'Pachuca', 37, 108],
    ['Jhonder Cadiz', 'FWD', 9, 'Leon', 30, 12],
    ['Yeferson Soteldo', 'FWD', 7, 'Santos', 28, 42],
    ['Darwin Machis', 'FWD', 11, 'Cadiz', 33, 48],
  ]),
  s('ALG', 'Algeria', '🇩🇿', 'M', '4-3-3', 'Vladimir Petkovic', [
    ['Anthony Mandrea', 'GK', 23, 'Caen', 28, 18],
    ['Aissa Mandi', 'DEF', 5, 'Lille', 33, 92],
    ['Ramy Bensebaini', 'DEF', 2, 'Borussia Dortmund', 31, 68],
    ['Rayan Ait-Nouri', 'DEF', 3, 'Wolves', 25, 12],
    ['Ismael Bennacer', 'MID', 8, 'Marseille', 28, 50],
    ['Houssem Aouar', 'MID', 6, 'Al-Ittihad', 27, 15],
    ['Riyad Mahrez', 'FWD', 7, 'Al-Ahli', 35, 98],
    ['Mohamed Amoura', 'FWD', 9, 'Wolfsburg', 26, 28],
    ['Said Benrahma', 'FWD', 10, 'Lyon', 30, 32],
    ['Amine Gouiri', 'FWD', 11, 'Marseille', 25, 12],
    ['Baghdad Bounedjah', 'FWD', 13, 'Al-Sadd', 34, 68],
  ]),
  s('TUN', 'Tunisia', '🇹🇳', 'N', '4-3-3', 'Faouzi Benzarti', [
    ['Aymen Dahmen', 'GK', 16, 'Al-Hazem', 28, 18],
    ['Yassine Meriah', 'DEF', 6, 'Esperance Tunis', 32, 82],
    ['Montassar Talbi', 'DEF', 3, 'Lorient', 28, 42],
    ['Ali Abdi', 'DEF', 14, 'Nice', 31, 28],
    ['Ellyes Skhiri', 'MID', 17, 'Eintracht Frankfurt', 31, 68],
    ['Aissa Laidouni', 'MID', 5, 'Al-Wakrah', 29, 48],
    ['Hannibal Mejbri', 'MID', 8, 'Burnley', 24, 32],
    ['Anis Ben Slimane', 'MID', 10, 'Norwich City', 25, 35],
    ['Youssef Msakni', 'FWD', 7, 'Al-Arabi', 35, 102],
    ['Seifeddine Jaziri', 'FWD', 9, 'Zamalek', 33, 38],
    ['Elias Achouri', 'FWD', 11, 'FC Copenhagen', 26, 15],
  ]),
  s('GRE', 'Greece', '🇬🇷', 'O', '4-3-3', 'Ivan Jovanovic', [
    ['Odysseas Vlachodimos', 'GK', 1, 'Newcastle', 32, 42],
    ['Konstantinos Mavropanos', 'DEF', 4, 'West Ham', 27, 30],
    ['Kostas Tsimikas', 'DEF', 21, 'Liverpool', 29, 38],
    ['Panagiotis Retsos', 'DEF', 3, 'Olympiacos', 28, 15],
    ['Anastasios Bakasetas', 'MID', 8, 'Panathinaikos', 32, 68],
    ['Dimitrios Pelkas', 'MID', 10, 'Basaksehir', 31, 42],
    ['Christos Tzolis', 'MID', 7, 'Club Brugge', 24, 15],
    ['Giorgos Giakoumakis', 'FWD', 9, 'Atlanta United', 31, 28],
    ['Vangelis Pavlidis', 'FWD', 17, 'Benfica', 27, 42],
    ['Fotis Ioannidis', 'FWD', 11, 'Panathinaikos', 26, 12],
    ['Giorgos Masouras', 'FWD', 19, 'Olympiacos', 31, 42],
  ]),
];

export default squads;
