// Official World Cup 2026 squad data
// Source: Dân Trí, June 4 2026
// Jersey numbers are approximate (not in source)

export interface Player {
  name: string;
  position: 'GK' | 'DEF' | 'MID' | 'FWD';
  number: number;
  club?: string;
  age?: number;
  caps?: number;
}

export interface Squad {
  teamCode: string;
  teamName: string;
  flag: string;
  group: string;
  formation: string;
  coach: string;
  players: Player[];
}

function s(
  code: string, name: string, flag: string, group: string, formation: string, coach: string,
  players: [string, Player['position'], number, string?][],
): Squad {
  return { teamCode: code, teamName: name, flag, group, formation, coach,
    players: players.map(([pname, pos, num, club]) => ({ name: pname, position: pos, number: num, club })),
  };
}

const squads: Squad[] = [

  // ═══ GROUP A ═══
  s('CZE', 'Czech Republic', '🇨🇿', 'A', '4-2-3-1', 'Miroslav Koubek', [
    ['Lukáš Horníček', 'GK', 1, 'Braga'], ['Matěj Kovář', 'GK', 16, 'PSV Eindhoven'], ['Jindřich Staněk', 'GK', 23, 'Slavia Prague'],
    ['Vladimír Coufal', 'DEF', 5, 'Hoffenheim'], ['David Douděra', 'DEF', 2, 'Slavia Prague'], ['Tomáš Holeš', 'DEF', 3, 'Slavia Prague'],
    ['Robin Hranáč', 'DEF', 4, 'Hoffenheim'], ['Štěpán Chaloupek', 'DEF', 6, 'Slavia Prague'], ['David Jurásek', 'DEF', 13, 'Slavia Prague'],
    ['Ladislav Krejčí', 'DEF', 15, 'Wolverhampton'], ['Jaroslav Zelený', 'DEF', 12, 'Sparta Prague'], ['David Zima', 'DEF', 14, 'Slavia Prague'],
    ['Tomáš Souček', 'MID', 8, 'West Ham'], ['Lukáš Provod', 'MID', 7, 'Slavia Prague'], ['Michal Sadílek', 'MID', 17, 'Slavia Prague'],
    ['Pavel Šulc', 'MID', 10, 'Lyon'], ['Lukáš Červ', 'MID', 18, 'Viktoria Plzeň'], ['Vladimír Darida', 'MID', 20, 'Hradec Králové'],
    ['Alexandr Sojka', 'MID', 19, 'Viktoria Plzeň'], ['Denis Višinský', 'MID', 21, 'Viktoria Plzeň'],
    ['Patrik Schick', 'FWD', 9, 'Bayer Leverkusen'], ['Adam Hložek', 'FWD', 11, 'Hoffenheim'], ['Tomáš Chorý', 'FWD', 22, 'Slavia Prague'],
    ['Mojmír Chytil', 'FWD', 14, 'Slavia Prague'], ['Jan Kuchta', 'FWD', 19, 'Sparta Prague'],
  ]),
  s('MEX', 'Mexico', '🇲🇽', 'A', '4-3-3', 'Javier Aguirre', [
    ['Raúl Rangel', 'GK', 1, 'Chivas'], ['Guillermo Ochoa', 'GK', 13, 'AEL Limassol'], ['Carlos Acevedo', 'GK', 12, 'Santos Laguna'],
    ['Johan Vásquez', 'DEF', 5, 'Genoa'], ['César Montes', 'DEF', 3, 'Lokomotiv Moscow'], ['Jesús Gallardo', 'DEF', 23, 'Toluca'],
    ['Jorge Sánchez', 'DEF', 2, 'PAOK'], ['Mateo Chávez', 'DEF', 4, 'AZ Alkmaar'], ['Israel Reyes', 'DEF', 6, 'Club América'],
    ['Edson Álvarez', 'MID', 18, 'Fenerbahce'], ['Orbelín Pineda', 'MID', 17, 'AEK Athens'], ['Álvaro Fidalgo', 'MID', 8, 'Real Betis'],
    ['Obed Vargas', 'MID', 14, 'Atletico Madrid'], ['Gilberto Mora', 'MID', 20, 'Tijuana'], ['Luis Chávez', 'MID', 24, 'Dynamo Moscow'],
    ['Érik Lira', 'MID', 15, 'Cruz Azul'], ['Luis Romo', 'MID', 7, 'Chivas'],
    ['Santiago Giménez', 'FWD', 9, 'AC Milan'], ['Raúl Jiménez', 'FWD', 10, 'Fulham'], ['César Huerta', 'FWD', 21, 'Anderlecht'],
    ['Armando González', 'FWD', 11, 'Chivas'], ['Guillermo Martínez', 'FWD', 19, 'Pumas'], ['Alexis Vega', 'FWD', 22, 'Toluca'],
  ]),
  s('RSA', 'South Africa', '🇿🇦', 'A', '4-4-2', 'Hugo Broos', [
    ['Ronwen Williams', 'GK', 1, 'Mamelodi Sundowns'], ['Sipho Chaine', 'GK', 16, 'Orlando Pirates'], ['Ricardo Goss', 'GK', 22, 'Siwelele'],
    ['Aubrey Modiba', 'DEF', 6, 'Sundowns'], ['Khuliso Mudau', 'DEF', 2, 'Sundowns'], ['Khulumani Ndamane', 'DEF', 3, 'Sundowns'],
    ['Nkosinathi Sibisi', 'DEF', 4, 'Pirates'], ['Bradley Cross', 'DEF', 5, 'Kaizer Chiefs'], ['Samukele Kabini', 'DEF', 13, 'Molde'],
    ['Olwethu Makhanya', 'DEF', 14, 'Philadelphia Union'], ['Thabang Matuludi', 'DEF', 15, 'Polokwane City'],
    ['Ime Okon', 'DEF', 17, 'Hannover'],
    ['Teboho Mokoena', 'MID', 8, 'Sundowns'], ['Themba Zwane', 'MID', 10, 'Sundowns'], ['Sphephelo Sithole', 'MID', 15, 'Tondela'],
    ['Oswin Appollis', 'MID', 11, 'Pirates'], ['Thalente Mbatha', 'MID', 18, 'Pirates'], ['Relebohile Mofokeng', 'MID', 7, 'Pirates'],
    ['Jayden Adams', 'MID', 20, 'Sundowns'],
    ['Lyle Foster', 'FWD', 9, 'Burnley'], ['Evidence Makgopa', 'FWD', 21, 'Pirates'], ['Tshepang Moremi', 'FWD', 19, 'Pirates'],
    ['Thapelo Maseko', 'FWD', 17, 'AEL Limassol'], ['Iqraam Rayners', 'FWD', 23, 'Sundowns'],
  ]),
  s('KOR', 'South Korea', '🇰🇷', 'A', '4-4-2', 'Hong Myung-bo', [
    ['Jo Hyeon-woo', 'GK', 21, 'Ulsan HD'], ['Kim Seung-gyu', 'GK', 1, 'FC Tokyo'], ['Song Bum-keun', 'GK', 12, 'Jeonbuk Hyundai'],
    ['Kim Min-jae', 'DEF', 4, 'Bayern Munich'], ['Cho Yu-min', 'DEF', 5, 'Sharjah'], ['Lee Han-beom', 'DEF', 3, 'Midtjylland'],
    ['Kim Tae-hyeon', 'DEF', 2, 'Kashima Antlers'], ['Park Jin-seob', 'DEF', 6, 'Zhejiang FC'], ['Lee Ki-hyuk', 'DEF', 15, 'Gangwon FC'],
    ['Lee Tae-seok', 'DEF', 14, 'Austria Vienna'], ['Seol Young-woo', 'DEF', 22, 'Red Star Belgrade'],
    ['Jens Castrop', 'DEF', 13, 'Borussia Mönchengladbach'],
    ['Son Heung-min', 'FWD', 7, 'LAFC'], ['Lee Kang-in', 'MID', 18, 'Paris Saint-Germain'], ['Hwang In-beom', 'MID', 6, 'Feyenoord'],
    ['Lee Jae-sung', 'MID', 10, 'Mainz'], ['Paik Seung-ho', 'MID', 13, 'Birmingham City'], ['Yang Hyun-jun', 'MID', 17, 'Celtic'],
    ['Bae Jun-ho', 'MID', 8, 'Stoke City'], ['Eom Ji-sung', 'MID', 11, 'Swansea City'], ['Lee Dong-gyeong', 'MID', 20, 'Ulsan HD'],
    ['Hwang Hee-chan', 'FWD', 11, 'Wolverhampton'], ['Cho Gue-sung', 'FWD', 9, 'Midtjylland'], ['Oh Hyeon-gyu', 'FWD', 20, 'Beşiktaş'],
  ]),

  // ═══ GROUP B ═══
  s('BIH', 'Bosnia & Herzegovina', '🇧🇦', 'B', '4-4-2', 'Sergej Barbarez', [
    ['Nikola Vasilj', 'GK', 1, 'FC St. Pauli'], ['Martin Zlomislić', 'GK', 12, 'HNK Rijeka'], ['Osman Hadžikić', 'GK', 22, 'Slaven Belupo'],
    ['Sead Kolašinac', 'DEF', 5, 'Atalanta'], ['Amar Dedić', 'DEF', 2, 'Benfica'], ['Nihad Mujakić', 'DEF', 3, 'Gaziantep FK'],
    ['Nikola Katić', 'DEF', 4, 'Schalke 04'], ['Tarik Muharemović', 'DEF', 15, 'Sassuolo'], ['Stjepan Radeljić', 'DEF', 13, 'Rijeka'],
    ['Dennis Hadžikadunić', 'DEF', 6, 'Sampdoria'], ['Nidal Čelik', 'DEF', 14, 'Lens'],
    ['Amir Hadžiahmetović', 'MID', 8, 'Hull City'], ['Ivan Šunjić', 'MID', 16, 'Pafos FC'], ['Ivan Bašić', 'MID', 10, 'FC Astana'],
    ['Benjamin Tahirović', 'MID', 7, 'Brøndby IF'], ['Amar Memić', 'MID', 19, 'Viktoria Plzen'], ['Armin Gigović', 'MID', 18, 'Young Boys'],
    ['Edin Džeko', 'FWD', 11, 'Schalke 04'], ['Ermedin Demirović', 'FWD', 9, 'VfB Stuttgart'],
    ['Esmir Bajraktarević', 'FWD', 17, 'PSV Eindhoven'], ['Haris Tabaković', 'FWD', 21, 'Borussia Mönchengladbach'],
    ['Samed Baždar', 'FWD', 20, 'Jagiellonia Białystok'],
  ]),
  s('CAN', 'Canada', '🇨🇦', 'B', '4-4-2', 'Jesse Marsch', [
    ['Dayne St. Clair', 'GK', 1, 'Inter Miami'], ['Maxime Crépeau', 'GK', 16, 'Orlando City'], ['Owen Goodman', 'GK', 18, 'Barnsley'],
    ['Alphonso Davies', 'DEF', 19, 'Bayern Munich'], ['Moïse Bombito', 'DEF', 5, 'Nice'], ['Derek Cornelius', 'DEF', 4, 'Marseille'],
    ['Alistair Johnston', 'DEF', 2, 'Celtic'], ['Luc de Fougerolles', 'DEF', 22, 'Fulham'], ['Richie Laryea', 'DEF', 15, 'Toronto FC'],
    ['Niko Sigur', 'DEF', 3, 'Hadjuk Split'], ['Joel Waterman', 'DEF', 6, 'Chicago Fire'],
    ['Stephen Eustáquio', 'MID', 7, 'Porto'], ['Ismaël Koné', 'MID', 8, 'Sassuolo'], ['Tajon Buchanan', 'MID', 17, 'Villarreal'],
    ['Jonathan Oscorio', 'MID', 21, 'Toronto FC'], ['Mathieu Choinière', 'MID', 13, 'LAFC'], ['Ali Ahmed', 'MID', 20, 'Norwich City'],
    ['Nathan Saliba', 'MID', 14, 'Anderlecht'], ['Jacob Shaffelburg', 'MID', 23, 'LAFC'],
    ['Jonathan David', 'FWD', 10, 'Juventus'], ['Cyle Larin', 'FWD', 9, 'Mallorca'], ['Promise David', 'FWD', 11, 'Union Saint-Gilloise'],
    ['Tani Olywaseyi', 'FWD', 12, 'Villarreal'], ['Liam Millar', 'FWD', 18, 'Hull City'],
  ]),
  s('QAT', 'Qatar', '🇶🇦', 'B', '4-3-3', 'Julen Lopetegui', [
    ['Meshaal Barsham', 'GK', 1, 'Al Sadd'], ['Salah Zakaria', 'GK', 21, 'Al Duhail'], ['Shehab Ellethy', 'GK', 22, 'Al Shahania'],
    ['Boualem Khoukhi', 'DEF', 16, 'Al Sadd'], ['Pedro Miguel', 'DEF', 2, 'Al Sadd'], ['Tarek Salman', 'DEF', 5, 'Al Sadd'],
    ['Sultan Al-Brake', 'DEF', 3, 'Al Duhail'], ['Lucas Mendes', 'DEF', 4, 'Al Wakrah'], ['Bassam Al-Rawi', 'DEF', 15, 'Al Duhail'],
    ['Mohammed Waad', 'DEF', 13, 'Al Shamal'],
    ['Abdulaziz Hatem', 'MID', 6, 'Al Rayyan'], ['Karim Boudiaf', 'MID', 8, 'Al Duhail'], ['Jassim Gaber', 'MID', 23, 'Al Rayyan'],
    ['Ahmed Fathy', 'MID', 14, 'Al Arabi'], ['Assim Madibo', 'MID', 17, 'Al Wakrah'],
    ['Akram Afif', 'FWD', 11, 'Al Sadd'], ['Almoez Ali', 'FWD', 19, 'Al Duhail'], ['Hassan Al-Haydos', 'FWD', 10, 'Al Sadd'],
    ['Yusuf Abdurisag', 'FWD', 9, 'Al Wakrah'], ['Edmílson Junior', 'FWD', 7, 'Al Duhail'],
    ['Ahmed Alaa', 'FWD', 18, 'Al Rayyan'], ['Mohammed Muntari', 'FWD', 20, 'Al Gharafa'],
  ]),
  s('SUI', 'Switzerland', '🇨🇭', 'B', '4-2-3-1', 'Murat Yakin', [
    ['Gregor Kobel', 'GK', 1, 'Borussia Dortmund'], ['Yvon Mvogo', 'GK', 12, 'Lorient'], ['Marvin Keller', 'GK', 21, 'Young Boys'],
    ['Manuel Akanji', 'DEF', 5, 'Inter Milan'], ['Nico Elvedi', 'DEF', 4, 'Borussia Mönchengladbach'], ['Ricardo Rodriguez', 'DEF', 13, 'Real Betis'],
    ['Silvan Widmer', 'DEF', 3, 'Mainz'], ['Miro Muheim', 'DEF', 2, 'Hamburger SV'], ['Aurèle Amenda', 'DEF', 15, 'Eintracht Frankfurt'],
    ['Eray Cömert', 'DEF', 6, 'Valencia'], ['Luca Jaquez', 'DEF', 22, 'Stuttgart'],
    ['Granit Xhaka', 'MID', 10, 'Sunderland'], ['Remo Freuler', 'MID', 8, 'Bologna'], ['Denis Zakaria', 'MID', 6, 'Monaco'],
    ['Ardon Jashari', 'MID', 20, 'AC Milan'], ['Djibril Sow', 'MID', 14, 'Sevilla'], ['Michel Aebischer', 'MID', 19, 'Pisa'],
    ['Fabian Rieder', 'MID', 17, 'Augsburg'], ['Rubén Vargas', 'MID', 7, 'Sevilla'],
    ['Breel Embolo', 'FWD', 9, 'Rennes'], ['Dan Ndoye', 'FWD', 11, 'Nottingham Forest'], ['Noah Okafor', 'FWD', 18, 'Leeds'],
    ['Zeki Amdouni', 'FWD', 23, 'Burnley'],
  ]),

  // ═══ GROUP C ═══
  s('BRA', 'Brazil', '🇧🇷', 'C', '4-2-3-1', 'Carlo Ancelotti', [
    ['Alisson', 'GK', 1, 'Liverpool'], ['Ederson', 'GK', 23, 'Fenerbahçe'], ['Weverton', 'GK', 12, 'Gremio'],
    ['Marquinhos', 'DEF', 4, 'Paris Saint-Germain'], ['Gabriel Magalhães', 'DEF', 14, 'Arsenal'], ['Bremer', 'DEF', 3, 'Juventus'],
    ['Ibañez', 'DEF', 2, 'Al-Ahli'], ['Wesley', 'DEF', 6, 'Roma'], ['Alex Sandro', 'DEF', 13, 'Flamengo'],
    ['Danilo', 'DEF', 15, 'Flamengo'], ['Douglas Santos', 'DEF', 16, 'Zenit'],
    ['Bruno Guimarães', 'MID', 8, 'Newcastle'], ['Casemiro', 'MID', 5, 'Manchester United'], ['Fabinho', 'MID', 17, 'Al-Ittihad'],
    ['Lucas Paquetá', 'MID', 10, 'Flamengo'], ['Danilo Santos', 'MID', 18, 'Botafogo'],
    ['Vinícius Júnior', 'FWD', 7, 'Real Madrid'], ['Neymar', 'FWD', 11, 'Santos'], ['Raphinha', 'FWD', 19, 'Barcelona'],
    ['Endrick', 'FWD', 9, 'Lyon'], ['Gabriel Martinelli', 'FWD', 21, 'Arsenal'], ['Matheus Cunha', 'FWD', 20, 'Manchester United'],
    ['Luiz Henrique', 'FWD', 22, 'Zenit'], ['Rayan', 'FWD', 24, 'Bournemouth'], ['Igor Thiago', 'FWD', 25, 'Brentford'],
  ]),
  s('HAI', 'Haiti', '🇭🇹', 'C', '4-4-2', 'Sébastien Migné', [
    ['Johny Placide', 'GK', 1, 'Bastia'], ['Alexandre Pierre', 'GK', 12, 'Sochaux'], ['Josué Duverger', 'GK', 23, 'Cosmos Koblenz'],
    ['Carlens Arcus', 'DEF', 2, 'Angers'], ['Ricardo Adé', 'DEF', 4, 'LDU Quito'], ['Jean-Kévin Duverne', 'DEF', 5, 'Gent'],
    ['Hannes Delcroix', 'DEF', 3, 'Lugano'], ['Martin Expérience', 'DEF', 15, 'Nancy'], ['Duke Lacroix', 'DEF', 6, 'Colorado Springs'],
    ['Wilguens Paugain', 'DEF', 13, 'Zulte Waregem'],
    ['Danley Jean Jacques', 'MID', 8, 'Philadelphia Union'], ['Jean-Ricner Bellegarde', 'MID', 10, 'Wolves'],
    ['Leverton Pierre', 'MID', 17, 'Vizela'], ['Carl Sainté', 'MID', 14, 'El Paso Locomotive'],
    ['Frantzdy Pierrot', 'FWD', 9, 'Çaykur Rizespor'], ['Duckens Nazon', 'FWD', 7, 'Esteghlal'],
    ['Don Deedson Louicius', 'FWD', 11, 'FC Dallas'], ['Derrick Etienne', 'FWD', 19, 'Toronto FC'],
    ['Wilson Isidor', 'FWD', 20, 'Sunderland'], ['Yassin Fortuné', 'FWD', 21, 'Vizela'], ['Lenny Joseph', 'FWD', 22, 'Ferencváros'],
  ]),
  s('MAR', 'Morocco', '🇲🇦', 'C', '4-3-3', 'Mohamed Ouahbi', [
    ['Yassine Bounou', 'GK', 1, 'Al-Hilal'], ['Munir El Kajoui', 'GK', 12, 'Berkane'], ['Ahmed Reda Tagnaouti', 'GK', 22, 'Asfar'],
    ['Achraf Hakimi', 'DEF', 2, 'Paris Saint-Germain'], ['Noussair Mazraoui', 'DEF', 3, 'Manchester United'],
    ['Nayef Aguerd', 'DEF', 5, 'Marseille'], ['Issa Diop', 'DEF', 6, 'Fulham'], ['Chadi Riad', 'DEF', 13, 'Crystal Palace'],
    ['Zakaria El Ouahdi', 'DEF', 15, 'Genk'], ['Redouane Halhal', 'DEF', 4, 'KV Mechelen'],
    ['Sofyan Amrabat', 'MID', 4, 'Real Betis'], ['Azzedine Ounahi', 'MID', 8, 'Girona'], ['Bilal El Khannouss', 'MID', 15, 'Stuttgart'],
    ['Ayyoub Bouaddi', 'MID', 6, 'Lille'], ['Neil El Aynaoui', 'MID', 23, 'Roma'], ['Ismael Saibari', 'MID', 14, 'PSV'],
    ['Brahim Díaz', 'FWD', 10, 'Real Madrid'], ['Ayoub El Kaabi', 'FWD', 9, 'Olympiacos'],
    ['Abde Ezzalzouli', 'FWD', 17, 'Real Betis'], ['Soufiane Rahimi', 'FWD', 21, 'Al-Ain'],
    ['Chemsdine Talbi', 'FWD', 7, 'Sunderland'], ['Yassine Gessime', 'FWD', 11, 'Strasbourg'],
  ]),
  s('SCO', 'Scotland', '🏴󠁧󠁢󠁳󠁣󠁴󠁿', 'C', '4-4-2', 'Steve Clarke', [
    ['Angus Gunn', 'GK', 1, 'Nottingham Forest'], ['Craig Gordon', 'GK', 12, 'Hearts'], ['Liam Kelly', 'GK', 21, 'Rangers'],
    ['Andy Robertson', 'DEF', 3, 'Liverpool'], ['Kieran Tierney', 'DEF', 5, 'Celtic'], ['Aaron Hickey', 'DEF', 2, 'Brentford'],
    ['Nathan Patterson', 'DEF', 22, 'Everton'], ['Grant Hanley', 'DEF', 4, 'Hibernian'], ['Jack Hendry', 'DEF', 6, 'Al-Ettifaq'],
    ['John Souttar', 'DEF', 15, 'Rangers'], ['Scott McKenna', 'DEF', 13, 'Dinamo Zagreb'], ['Anthony Ralston', 'DEF', 16, 'Celtic'],
    ['Scott McTominay', 'MID', 8, 'Napoli'], ['John McGinn', 'MID', 7, 'Aston Villa'], ['Billy Gilmour', 'MID', 14, 'Napoli'],
    ['Ryan Christie', 'MID', 11, 'Bournemouth'], ['Lewis Ferguson', 'MID', 10, 'Bologna'], ['Ben Gannon-Doak', 'MID', 18, 'Bournemouth'],
    ['Lawrence Shankland', 'FWD', 9, 'Hearts'], ['Ché Adams', 'FWD', 19, 'Torino'], ['Lyndon Dykes', 'FWD', 20, 'Charlton'],
    ['George Hirst', 'FWD', 23, 'Ipswich'],
  ]),

  // ═══ GROUP D ═══
  s('AUS', 'Australia', '🇦🇺', 'D', '4-4-2', 'Tony Popovic', [
    ['Mat Ryan', 'GK', 1, 'Levante'], ['Patrick Beach', 'GK', 12, 'Melbourne City'], ['Paul Izzo', 'GK', 18, 'Randers FC'],
    ['Harry Souttar', 'DEF', 19, 'Leicester City'], ['Cameron Burgess', 'DEF', 4, 'Swansea City'], ['Alessandro Circati', 'DEF', 5, 'Parma'],
    ['Aziz Behich', 'DEF', 16, 'Melbourne City'], ['Jordan Bos', 'DEF', 3, 'Feyenoord'], ['Milos Degenek', 'DEF', 2, 'Apoel FC'],
    ['Jason Geria', 'DEF', 14, 'Albirex Niigata'], ['Kai Trewin', 'DEF', 6, 'NYCFC'],
    ['Jackson Irvine', 'MID', 22, 'St. Pauli'], ['Connor Metcalfe', 'MID', 8, 'St. Pauli'], ['Mathew Leckie', 'MID', 7, 'Melbourne City'],
    ['Aiden O\'Neill', 'MID', 13, 'NYCFC'], ['Ajdin Hrustic', 'MID', 10, 'Heracles Almelo'], ['Cristian Volpato', 'MID', 17, 'Sassuolo'],
    ['Nestory Irankunda', 'FWD', 20, 'Watford'], ['Awer Mabil', 'FWD', 11, 'CD Castellón'], ['Mohamed Toure', 'FWD', 9, 'Norwich City'],
    ['Nishan Velupillay', 'FWD', 21, 'Melbourne Victory'], ['Tete Yengi', 'FWD', 15, 'Machida Zelvia'],
  ]),
  s('PAR', 'Paraguay', '🇵🇾', 'D', '4-4-2', 'Gustavo Alfaro', [
    ['Roberto Junior Fernandez', 'GK', 1, 'Cerro Porteno'], ['Orlando Gill', 'GK', 12, 'San Lorenzo'], ['Gaston Olveira', 'GK', 22, 'Olimpia'],
    ['Gustavo Gomez', 'DEF', 15, 'Palmeiras'], ['Fabian Balbuena', 'DEF', 5, 'Gremio'], ['Omar Alderete', 'DEF', 3, 'Sunderland'],
    ['Junior Alonso', 'DEF', 2, 'Atletico Mineiro'], ['Gustavo Velazquez', 'DEF', 4, 'Cerro Porteno'],
    ['Alexandro Maidana', 'DEF', 13, 'Talleres'], ['Juan Jose Caceres', 'DEF', 6, 'Dinamo Moscow'],
    ['Diego Gomez', 'MID', 8, 'Brighton'], ['Andres Cubas', 'MID', 14, 'Vancouver Whitecaps'],
    ['Matias Galarza', 'MID', 17, 'Atlanta United'], ['Damian Bobadilla', 'MID', 20, 'Sao Paulo'],
    ['Alejandro Romero', 'MID', 10, 'Al Ain'], ['Gustavo Caballero', 'MID', 18, 'Portsmouth'],
    ['Miguel Almiron', 'FWD', 10, 'Atlanta United'], ['Julio Enciso', 'FWD', 11, 'Strasbourg'], ['Ramon Sosa', 'FWD', 7, 'Palmeiras'],
    ['Antonio Sanabria', 'FWD', 9, 'Cremonese'], ['Gabriel Avalos', 'FWD', 19, 'Independiente'],
  ]),
  s('TUR', 'Turkey', '🇹🇷', 'D', '4-2-3-1', 'Vincenzo Montella', [
    ['Altay Bayındır', 'GK', 1, 'Manchester United'], ['Mert Günok', 'GK', 12, 'Fenerbahçe'], ['Uğurcan Çakır', 'GK', 23, 'Galatasaray'],
    ['Çağlar Söyüncü', 'DEF', 4, 'Fenerbahçe'], ['Merih Demiral', 'DEF', 3, 'Al Ahli'], ['Ozan Kabak', 'DEF', 5, 'Hoffenheim'],
    ['Ferdi Kadıoğlu', 'DEF', 20, 'Brighton'], ['Zeki Çelik', 'DEF', 2, 'Roma'], ['Mert Müldür', 'DEF', 22, 'Fenerbahçe'],
    ['Eren Elmalı', 'DEF', 13, 'Galatasaray'], ['Abdülkerim Bardakcı', 'DEF', 15, 'Galatasaray'],
    ['Hakan Çalhanoğlu', 'MID', 10, 'Inter'], ['Orkun Kökçü', 'MID', 6, 'Beşiktaş'], ['İsmail Yüksek', 'MID', 8, 'Fenerbahçe'],
    ['Salih Özcan', 'MID', 18, 'Borussia Dortmund'], ['Kaan Ayhan', 'MID', 14, 'Galatasaray'],
    ['Arda Güler', 'FWD', 11, 'Real Madrid'], ['Kenan Yıldız', 'FWD', 19, 'Juventus'], ['Kerem Aktürkoğlu', 'FWD', 7, 'Fenerbahçe'],
    ['Barış Alper Yılmaz', 'FWD', 9, 'Galatasaray'], ['Can Uzun', 'FWD', 17, 'Eintracht Frankfurt'], ['Deniz Gül', 'FWD', 21, 'Porto'],
  ]),
  s('USA', 'United States', '🇺🇸', 'D', '4-3-3', 'Mauricio Pochettino', [
    ['Matt Turner', 'GK', 1, 'New England'], ['Chris Brady', 'GK', 18, 'Chicago'], ['Matt Freese', 'GK', 25, 'New York City'],
    ['Antonee Robinson', 'DEF', 5, 'Fulham'], ['Sergiño Dest', 'DEF', 2, 'PSV Eindhoven'], ['Chris Richards', 'DEF', 15, 'Crystal Palace'],
    ['Mark McKenzie', 'DEF', 3, 'Toulouse'], ['Tim Ream', 'DEF', 13, 'Charlotte'], ['Joe Scally', 'DEF', 22, 'Mönchengladbach'],
    ['Miles Robinson', 'DEF', 4, 'Cincinnati'], ['Auston Trusty', 'DEF', 6, 'Celtic'],
    ['Weston McKennie', 'MID', 8, 'Juventus'], ['Tyler Adams', 'MID', 4, 'Bournemouth'], ['Gio Reyna', 'MID', 7, 'Mönchengladbach'],
    ['Malik Tillman', 'MID', 17, 'Bayer Leverkusen'], ['Cristian Roldan', 'MID', 10, 'Seattle'],
    ['Christian Pulisic', 'FWD', 10, 'AC Milan'], ['Folarin Balogun', 'FWD', 9, 'Monaco'], ['Ricardo Pepi', 'FWD', 21, 'PSV Eindhoven'],
    ['Tim Weah', 'FWD', 19, 'Marseille'], ['Brenden Aaronson', 'FWD', 11, 'Leeds'], ['Haji Wright', 'FWD', 14, 'Coventry City'],
  ]),

  // ═══ GROUP E ═══
  s('CUW', 'Curaçao', '🇨🇼', 'E', '4-3-3', 'Dick Advocaat', [
    ['Tyrick Bodak', 'GK', 1, 'SC Telstar'], ['Trevor Doornbusch', 'GK', 12, 'VVV-Venlo'], ['Eloy Room', 'GK', 22, 'Miami FC'],
    ['Riechedly Bazoer', 'DEF', 4, 'Konyaspor'], ['Joshua Brenet', 'DEF', 2, 'Kayserispor'], ['Armando Obispo', 'DEF', 3, 'PSV Eindhoven'],
    ['Shurandy Sambo', 'DEF', 5, 'Sparta Rotterdam'], ['Roshon Van Eijma', 'DEF', 13, 'RKC Waalwijk'],
    ['Sherel Floranus', 'DEF', 15, 'PEC Zwolle'], ['Juriën Gaari', 'DEF', 6, 'Abha Club'],
    ['Juninho Bacuna', 'MID', 8, 'FC Volendam'], ['Leandro Bacuna', 'MID', 10, 'Igdır'], ['Kevin Felida', 'MID', 18, 'FC Den Bosch'],
    ['Livano Comenencia', 'MID', 14, 'FC Zurich'], ['Godfried Roemeratoe', 'MID', 16, 'RKC Waalwijk'],
    ['Tahith Chong', 'FWD', 7, 'Sheffield United'], ['Kenji Gorré', 'FWD', 11, 'Maccabi Haifa'],
    ['Sontje Hansen', 'FWD', 9, 'Middlesbrough'], ['Gervane Kastaneer', 'FWD', 17, 'Terengganu FC'],
    ['Jürgen Locadia', 'FWD', 19, 'Miami FC'], ['Brandley Kuwas', 'FWD', 21, 'FC Volendam'],
  ]),
  s('ECU', 'Ecuador', '🇪🇨', 'E', '4-4-2', 'Sebastián Beccacece', [
    ['Hernán Galíndez', 'GK', 1, 'Huracan'], ['Moisés Ramírez', 'GK', 12, 'Kifisia'], ['Gonzalo Valle', 'GK', 22, 'Liga de Quito'],
    ['Piero Hincapié', 'DEF', 3, 'Arsenal'], ['Pervis Estupiñán', 'DEF', 7, 'AC Milan'], ['Willian Pacho', 'DEF', 2, 'Paris Saint-Germain'],
    ['Joel Ordonez', 'DEF', 4, 'Club Brugge'], ['Félix Torres', 'DEF', 5, 'Internacional'], ['Ángelo Preciado', 'DEF', 17, 'Atletico Mineiro'],
    ['Jackson Porozo', 'DEF', 6, 'Tijuana'],
    ['Moisés Caicedo', 'MID', 23, 'Chelsea'], ['Kendry Páez', 'MID', 16, 'River Plate'], ['Alan Franco', 'MID', 21, 'Atletico Mineiro'],
    ['Gonzalo Plata', 'MID', 10, 'Flamengo'], ['Alan Minda', 'MID', 13, 'Atletico Mineiro'], ['John Yeboah', 'MID', 14, 'Venezia'],
    ['Jeremy Arevalo', 'MID', 15, 'Stuttgart'], ['Denil Castillo', 'MID', 18, 'Midtjylland'], ['Yaimar Medina', 'MID', 20, 'Genk'],
    ['Enner Valencia', 'FWD', 13, 'Pachuca'], ['Kevin Rodriguez', 'FWD', 11, 'Union Saint-Gilloise'],
    ['Nilson Angulo', 'FWD', 9, 'Sunderland'], ['Anthony Valencia', 'FWD', 19, 'Royal Antwerp'],
  ]),
  s('GER', 'Germany', '🇩🇪', 'E', '4-2-3-1', 'Julian Nagelsmann', [
    ['Manuel Neuer', 'GK', 1, 'Bayern Munich'], ['Oliver Baumann', 'GK', 12, 'Hoffenheim'], ['Alexander Nübel', 'GK', 22, 'Stuttgart'],
    ['Antonio Rüdiger', 'DEF', 2, 'Real Madrid'], ['Jonathan Tah', 'DEF', 4, 'Bayern Munich'], ['Nico Schlotterbeck', 'DEF', 15, 'Borussia Dortmund'],
    ['Joshua Kimmich', 'DEF', 6, 'Bayern Munich'], ['David Raum', 'DEF', 3, 'RB Leipzig'], ['Waldemar Anton', 'DEF', 5, 'Borussia Dortmund'],
    ['Malick Thiaw', 'DEF', 13, 'Newcastle'], ['Nathaniel Brown', 'DEF', 14, 'Eintracht Frankfurt'],
    ['Jamal Musiala', 'MID', 14, 'Bayern Munich'], ['Florian Wirtz', 'MID', 10, 'Liverpool'], ['Leon Goretzka', 'MID', 8, 'Bayern Munich'],
    ['Aleksandar Pavlović', 'MID', 25, 'Bayern Munich'], ['Angelo Stiller', 'MID', 6, 'Stuttgart'],
    ['Felix Nmecha', 'MID', 17, 'Borussia Dortmund'], ['Pascal Groß', 'MID', 5, 'Brighton'],
    ['Kai Havertz', 'FWD', 7, 'Arsenal'], ['Leroy Sané', 'FWD', 19, 'Galatasaray'], ['Deniz Undav', 'FWD', 26, 'Stuttgart'],
    ['Maximilian Beier', 'FWD', 9, 'Borussia Dortmund'], ['Nick Woltemade', 'FWD', 11, 'Newcastle'],
  ]),
  s('CIV', 'Ivory Coast', '🇨🇮', 'E', '4-3-3', 'Emerse Fae', [
    ['Yahia Fofana', 'GK', 1, 'Rizespor'], ['Mohamed Koné', 'GK', 16, 'Charleroi'], ['Alban Lafont', 'GK', 23, 'Panathinaikos'],
    ['Evan Ndicka', 'DEF', 3, 'Roma'], ['Ousmane Diomande', 'DEF', 5, 'Sporting'], ['Odilon Kossounou', 'DEF', 4, 'Atalanta'],
    ['Wilfried Singo', 'DEF', 2, 'Galatasaray'], ['Emmanuel Agbadou', 'DEF', 6, 'Wolverhampton'],
    ['Guéla Doué', 'DEF', 13, 'Strasbourg'], ['Ghislain Konan', 'DEF', 15, 'Gil Vicente'],
    ['Franck Kessie', 'MID', 8, 'Al Ahli'], ['Seko Fofana', 'MID', 10, 'Stade Rennais'], ['Ibrahim Sangaré', 'MID', 18, 'Nottingham Forest'],
    ['Jean Michaël Seri', 'MID', 14, 'NK Maribor'], ['Christ Oulaï', 'MID', 19, 'Trabzonspor'],
    ['Amad Diallo', 'FWD', 11, 'Manchester United'], ['Simon Adingra', 'FWD', 7, 'Monaco'], ['Nicolas Pépé', 'FWD', 9, 'Villarreal'],
    ['Oumar Diakité', 'FWD', 22, 'Cercle Brugge'], ['Ange-Yoan Bonny', 'FWD', 21, 'Inter Milan'],
    ['Evann Guessand', 'FWD', 17, 'Aston Villa'], ['Elye Wahi', 'FWD', 12, 'Nice'], ['Bazoumana Touré', 'FWD', 20, 'Hoffenheim'],
  ]),

  // ═══ GROUP F ═══
  s('JPN', 'Japan', '🇯🇵', 'F', '4-2-3-1', 'Hajime Moriyasu', [
    ['Zion Suzuki', 'GK', 23, 'Parma'], ['Keisuke Ōsako', 'GK', 1, 'Sanfrecce Hiroshima'], ['Tomoki Hayakawa', 'GK', 12, 'Kashima Antlers'],
    ['Takehiro Tomiyasu', 'DEF', 16, 'Ajax'], ['Ko Itakura', 'DEF', 4, 'Ajax'], ['Hiroki Ito', 'DEF', 22, 'Bayern Munich'],
    ['Yukinari Sugawara', 'DEF', 3, 'Werder Bremen'], ['Tsuyoshi Watanabe', 'DEF', 5, 'Feyenoord'],
    ['Shōgo Taniguchi', 'DEF', 2, 'Sint-Truiden'], ['Ayumu Seko', 'DEF', 15, 'Le Havre'],
    ['Wataru Endō', 'MID', 6, 'Liverpool'], ['Takefusa Kubo', 'MID', 15, 'Real Sociedad'], ['Daichi Kamada', 'MID', 17, 'Crystal Palace'],
    ['Ritsu Doan', 'MID', 10, 'Eintracht Frankfurt'], ['Junya Ito', 'MID', 14, 'Genk'], ['Ao Tanaka', 'MID', 8, 'Leeds United'],
    ['Keito Nakamura', 'MID', 13, 'Reims'], ['Kaishū Sano', 'MID', 18, 'Mainz'],
    ['Ayase Ueda', 'FWD', 9, 'Feyenoord'], ['Daizen Maeda', 'FWD', 11, 'Celtic'], ['Koki Ogawa', 'FWD', 19, 'NEC Nijmegen'],
    ['Kento Shiogai', 'FWD', 21, 'Wolfsburg'],
  ]),
  s('NED', 'Netherlands', '🇳🇱', 'F', '4-3-3', 'Ronald Koeman', [
    ['Bart Verbruggen', 'GK', 1, 'Brighton'], ['Mark Flekken', 'GK', 13, 'Bayer Leverkusen'], ['Robin Roefs', 'GK', 23, 'Sunderland'],
    ['Virgil van Dijk', 'DEF', 4, 'Liverpool'], ['Nathan Aké', 'DEF', 5, 'Manchester City'], ['Jurrien Timber', 'DEF', 3, 'Arsenal'],
    ['Denzel Dumfries', 'DEF', 22, 'Inter Milan'], ['Micky van de Ven', 'DEF', 6, 'Tottenham'],
    ['Jorrel Hato', 'DEF', 2, 'Chelsea'], ['Jan Paul van Hecke', 'DEF', 15, 'Brighton'],
    ['Frenkie de Jong', 'MID', 21, 'Barcelona'], ['Ryan Gravenberch', 'MID', 8, 'Liverpool'],
    ['Tijjani Reijnders', 'MID', 14, 'Manchester City'], ['Teun Koopmeiners', 'MID', 20, 'Juventus'],
    ['Marten de Roon', 'MID', 17, 'Atalanta'], ['Quinten Timber', 'MID', 16, 'Marseille'], ['Mats Wieffer', 'MID', 18, 'Brighton'],
    ['Cody Gakpo', 'FWD', 11, 'Liverpool'], ['Memphis Depay', 'FWD', 9, 'Corinthians'], ['Donyell Malen', 'FWD', 18, 'Roma'],
    ['Justin Kluivert', 'FWD', 19, 'Bournemouth'], ['Noa Lang', 'FWD', 7, 'Galatasaray'], ['Brian Brobbey', 'FWD', 10, 'Sunderland'],
    ['Wout Weghorst', 'FWD', 12, 'Ajax'],
  ]),
  s('SWE', 'Sweden', '🇸🇪', 'F', '4-4-2', 'Graham Potter', [
    ['Viktor Johansson', 'GK', 1, 'Stoke City'], ['Kristoffer Nordfeldt', 'GK', 12, 'AIK'], ['Jacob Widell Zetterström', 'GK', 23, 'Derby County'],
    ['Victor Lindelöf', 'DEF', 3, 'Aston Villa'], ['Isak Hien', 'DEF', 4, 'Atalanta'], ['Emil Holm', 'DEF', 2, 'Juventus'],
    ['Gabriel Gudmundsson', 'DEF', 6, 'Leeds United'], ['Carl Starfelt', 'DEF', 5, 'Celta de Vigo'],
    ['Gustaf Lagerbielke', 'DEF', 15, 'Braga'], ['Daniel Svensson', 'DEF', 13, 'Borussia Dortmund'],
    ['Emil Forsberg', 'MID', 10, 'New York Red Bulls'], ['Mattias Svanberg', 'MID', 7, 'Wolfsburg'],
    ['Lucas Bergvall', 'MID', 8, 'Tottenham'], ['Yasin Ayari', 'MID', 18, 'Brighton'], ['Jesper Karlström', 'MID', 17, 'Udinese'],
    ['Besfort Zeneli', 'MID', 20, 'Union St-Gilloise'],
    ['Alexander Isak', 'FWD', 9, 'Liverpool'], ['Viktor Gyökeres', 'FWD', 17, 'Arsenal'], ['Anthony Elanga', 'FWD', 21, 'Newcastle United'],
    ['Gustaf Nilsson', 'FWD', 11, 'Club Brugge'], ['Benjamin Nygren', 'FWD', 19, 'Celtic'],
  ]),
  s('TUN', 'Tunisia', '🇹🇳', 'F', '4-3-3', 'Sabri Lamouchi', [
    ['Aymen Dahman', 'GK', 16, 'CS Sfaxien'], ['Sabri Ben Hessen', 'GK', 1, 'ES Sahel'], ['Abdelmouhib Chamakh', 'GK', 22, 'Club Africain'],
    ['Montassar Talbi', 'DEF', 3, 'Lorient'], ['Ali Abdi', 'DEF', 14, 'Nice'], ['Dylan Bronn', 'DEF', 6, 'Servette FC'],
    ['Yan Valery', 'DEF', 2, 'Young Boys'], ['Omar Rekik', 'DEF', 5, 'NK Maribor'], ['Mohamed Amine Ben Hamida', 'DEF', 13, 'Esperance'],
    ['Ellyes Skhiri', 'MID', 17, 'Eintracht Frankfurt'], ['Hannibal', 'MID', 8, 'Burnley'], ['Anis Ben Slimane', 'MID', 10, 'Norwich City'],
    ['Rani Khedira', 'MID', 15, 'Union Berlin'], ['Ismaël Gharbi', 'MID', 20, 'Augsburg'],
    ['Elias Achouri', 'FWD', 11, 'FC Copenhagen'], ['Sebastian Tounekti', 'FWD', 7, 'Celtic'],
    ['Hazem Mastouri', 'FWD', 9, 'Dynamo Makhachkala'], ['Elias Saad', 'FWD', 19, 'Hannover 96'],
    ['Firas Chaouat', 'FWD', 21, 'Club Africain'], ['Mortadha Ben Ouanes', 'FWD', 18, 'Kasimpasa'],
  ]),

  // ═══ GROUP G ═══
  s('BEL', 'Belgium', '🇧🇪', 'G', '4-2-3-1', 'Rudi Garcia', [
    ['Thibaut Courtois', 'GK', 1, 'Real Madrid'], ['Senne Lammens', 'GK', 12, 'Manchester United'], ['Mike Penders', 'GK', 23, 'Strasbourg'],
    ['Timothy Castagne', 'DEF', 21, 'Fulham'], ['Zeno Debast', 'DEF', 2, 'Sporting CP'], ['Maxim de Cuyper', 'DEF', 3, 'Brighton'],
    ['Koni De Winter', 'DEF', 5, 'AC Milan'], ['Brandon Mechele', 'DEF', 4, 'Club Brugge'], ['Thomas Meunier', 'DEF', 15, 'Lille'],
    ['Arthur Theate', 'DEF', 6, 'Eintracht Frankfurt'], ['Joaquin Seys', 'DEF', 13, 'Club Brugge'],
    ['Kevin de Bruyne', 'MID', 7, 'Napoli'], ['Amadou Onana', 'MID', 6, 'Aston Villa'], ['Youri Tielemans', 'MID', 8, 'Aston Villa'],
    ['Hans Vanaken', 'MID', 17, 'Club Brugge'], ['Axel Witsel', 'MID', 18, 'Girona'], ['Nicolas Raskin', 'MID', 14, 'Rangers'],
    ['Romelu Lukaku', 'FWD', 9, 'Napoli'], ['Jérémy Doku', 'FWD', 11, 'Manchester City'],
    ['Charles De Ketelaere', 'FWD', 10, 'Atalanta'], ['Leandro Trossard', 'FWD', 19, 'Arsenal'],
    ['Dodi Lukébakio', 'FWD', 22, 'Benfica'], ['Alexis Saelemaekers', 'FWD', 20, 'AC Milan'],
  ]),
  s('EGY', 'Egypt', '🇪🇬', 'G', '4-3-3', 'Hossam Hassan', [
    ['Mohamed El Shenawy', 'GK', 1, 'Al Ahly'], ['Mostafa Shobeir', 'GK', 16, 'Al Ahly'], ['El-Mahdy Soliman', 'GK', 23, 'Zamalek'],
    ['Mohamed Abdelmonem', 'DEF', 2, 'Nice'], ['Ahmed Fatouh', 'DEF', 3, 'Zamalek'], ['Mohamed Hany', 'DEF', 6, 'Al Ahly'],
    ['Yasser Ibrahim', 'DEF', 5, 'Al Ahly'], ['Ramy Rabia', 'DEF', 4, 'Al Ain'], ['Karim Hafez', 'DEF', 12, 'Pyramids FC'],
    ['Mohamed Salah', 'MID', 10, 'Liverpool'], ['Emam Ashour', 'MID', 8, 'Al Ahly'], ['Zizo', 'MID', 7, 'Al Ahly'],
    ['Marwan Attia', 'MID', 14, 'Al Ahly'], ['Mahmoud Trézéguet', 'MID', 11, 'Al Ahly'],
    ['Nabil Emad', 'MID', 17, 'Al-Najma'], ['Ibrahim Adel', 'MID', 20, 'FC Nordsjælland'],
    ['Omar Marmoush', 'FWD', 9, 'Manchester City'], ['Mostafa Ziko', 'FWD', 21, 'Pyramids FC'],
    ['Aqtay Abdallah', 'FWD', 18, 'Enppi'], ['Hamza Abdelkarim', 'FWD', 19, 'Barcelona U19'],
  ]),
  s('IRN', 'Iran', '🇮🇷', 'G', '4-4-2', 'Amir Ghalenoei', [
    ['Alireza Beiranvand', 'GK', 1, 'Tractor'], ['Hossein Hosseini', 'GK', 12, 'Sepahan'], ['Payam Niazmand', 'GK', 22, 'Persepolis'],
    ['Shojae Khalilzadeh', 'DEF', 4, 'Tractor'], ['Hossein Kanaani', 'DEF', 13, 'Persepolis'], ['Ehsan Hajsafi', 'DEF', 3, 'Sepahan'],
    ['Ramin Rezaeian', 'DEF', 23, 'Foolad'], ['Milad Mohammadi', 'DEF', 5, 'Persepolis'],
    ['Ali Nemati', 'DEF', 2, 'Foolad'], ['Saleh Hardani', 'DEF', 15, 'Esteghlal'],
    ['Saeid Ezatolahi', 'MID', 6, 'Shabab Al-Ahli'], ['Saman Ghoddos', 'MID', 17, 'Kalba'],
    ['Alireza Jahanbakhsh', 'MID', 7, 'Dender'], ['Mehdi Ghaedi', 'MID', 11, 'Al-Nasr'], ['Mohammad Mohebi', 'MID', 10, 'Rostov'],
    ['Rouzbeh Cheshmi', 'MID', 8, 'Esteghlal'], ['Mehdi Torabi', 'MID', 16, 'Tractor'],
    ['Mehdi Taremi', 'FWD', 9, 'Olympiacos'], ['Sardar Azmoun', 'FWD', 20, 'Shabab Al-Ahli'],
    ['Ali Alipour', 'FWD', 19, 'Persepolis'], ['Dennis Eckert Ayensa', 'FWD', 14, 'Standard Liège'],
  ]),
  s('NZL', 'New Zealand', '🇳🇿', 'G', '4-4-2', 'Darren Bazeley', [
    ['Max Crocombe', 'GK', 1, 'Millwall'], ['Alex Paulsen', 'GK', 12, 'Lechia Gdańsk'], ['Michael Woud', 'GK', 22, 'Auckland FC'],
    ['Tyler Bindon', 'DEF', 5, 'Nottingham Forest'], ['Michael Boxall', 'DEF', 4, 'Minnesota United'],
    ['Liberato Cacace', 'DEF', 3, 'Wrexham'], ['Nando Pijnaker', 'DEF', 2, 'Auckland FC'],
    ['Tim Payne', 'DEF', 16, 'Wellington Phoenix'], ['Tommy Smith', 'DEF', 6, 'Braintree Town'],
    ['Finn Surman', 'DEF', 13, 'Portland Timbers'],
    ['Sarpreet Singh', 'MID', 10, 'Wellington Phoenix'], ['Marko Stamenić', 'MID', 6, 'Swansea City'],
    ['Joe Bell', 'MID', 8, 'Viking FK'], ['Matthew Garbett', 'MID', 15, 'Peterborough United'],
    ['Ryan Thomas', 'MID', 14, 'PEC Zwolle'], ['Ben Old', 'MID', 7, 'Saint-Étienne'],
    ['Chris Wood', 'FWD', 9, 'Nottingham Forest'], ['Ben Waine', 'FWD', 11, 'Port Vale'],
    ['Callum McCowatt', 'FWD', 17, 'Silkeborg'], ['Kosta Barbarouses', 'FWD', 18, 'Western Sydney Wanderers'],
    ['Eli Just', 'FWD', 20, 'Motherwell'],
  ]),

  // ═══ GROUP H ═══
  s('CPV', 'Cape Verde', '🇨🇻', 'H', '4-3-3', 'Pedro Leitão Brito', [
    ['Vozinha', 'GK', 1, 'Chaves'], ['CJ dos Santos', 'GK', 12, 'San Diego'], ['Márcio Rosa', 'GK', 22, 'Montana'],
    ['Logan Costa', 'DEF', 4, 'Villarreal'], ['Roberto Lopes', 'DEF', 2, 'Shamrock Rovers'], ['Steven Moreira', 'DEF', 3, 'Columbus Crew'],
    ['João Paulo', 'DEF', 5, 'FCSB'], ['Diney', 'DEF', 13, 'Al Bataeh'], ['Stopira', 'DEF', 15, 'Torreense'],
    ['Wagner Pina', 'DEF', 6, 'Trabzonspor'],
    ['Jamiro Monteiro', 'MID', 10, 'PEC Zwolle'], ['Kevin Pina', 'MID', 8, 'Krasnodar'], ['Deroy Duarte', 'MID', 14, 'Ludogorets'],
    ['Telmo Arcanjo', 'MID', 7, 'Vitoria Guimaraes'], ['Laros Duarte', 'MID', 18, 'Puskas Akademia'],
    ['Ryan Mendes', 'FWD', 11, 'Igdir'], ['Willy Semedo', 'FWD', 9, 'Omonia'], ['Jovane Cabral', 'FWD', 17, 'Estrela Amadora'],
    ['Hélio Varela', 'FWD', 19, 'Maccabi Tel Aviv'], ['Gilson Tavares', 'FWD', 21, 'Akron Tolyatti'],
    ['Nuno da Costa', 'FWD', 23, 'Istanbul Basaksehir'], ['Dailon Livramento', 'FWD', 20, 'Casa Pia'],
  ]),
  s('KSA', 'Saudi Arabia', '🇸🇦', 'H', '4-3-3', 'Georgios Donis', [
    ['Mohammed Al Owais', 'GK', 21, 'Al Ula'], ['Nawaf Al Aqidi', 'GK', 1, 'Al Nassr'], ['Ahmed Al-Kassar', 'GK', 12, 'Al Qadsiah'],
    ['Hassan Tambakti', 'DEF', 17, 'Al Hilal'], ['Ali Lajami', 'DEF', 5, 'Al Hilal'], ['Saud Abdulhamid', 'DEF', 2, 'Lens'],
    ['Abdulelah Al Amri', 'DEF', 4, 'Al Nassr'], ['Hassan Kadesh', 'DEF', 13, 'Al Ittihad'], ['Ali Majrashi', 'DEF', 6, 'Al Ahli'],
    ['Moteb Al Harbi', 'DEF', 3, 'Al Hilal'], ['Nawaf Boushal', 'DEF', 15, 'Al Nassr'],
    ['Salem Al Dawsari', 'MID', 10, 'Al Hilal'], ['Mohamed Kanno', 'MID', 28, 'Al Hilal'],
    ['Abdullah Al Khaibari', 'MID', 8, 'Al Nassr'], ['Nasser Al Dawsari', 'MID', 14, 'Al Hilal'],
    ['Musab Al Juwayr', 'MID', 18, 'Al Qadsiah'], ['Khalid Al Ghannam', 'MID', 11, 'Al-Ettifaq'], ['Ayman Yahya', 'MID', 7, 'Al Nassr'],
    ['Firas Al Buraikan', 'FWD', 9, 'Al Ahli'], ['Saleh Al Shehri', 'FWD', 11, 'Al Ittihad'], ['Abdullah Al Hamdan', 'FWD', 19, 'Al Nassr'],
  ]),
  s('ESP', 'Spain', '🇪🇸', 'H', '4-3-3', 'Luis de la Fuente', [
    ['Unai Simón', 'GK', 23, 'Athletic Club'], ['David Raya', 'GK', 1, 'Arsenal'], ['Joan García', 'GK', 13, 'Barcelona'],
    ['Pau Cubarsí', 'DEF', 4, 'Barcelona'], ['Aymeric Laporte', 'DEF', 3, 'Athletic Club'], ['Marc Cucurella', 'DEF', 12, 'Chelsea'],
    ['Alejandro Grimaldo', 'DEF', 2, 'Bayer Leverkusen'], ['Pedro Porro', 'DEF', 5, 'Tottenham'],
    ['Eric García', 'DEF', 14, 'Barcelona'], ['Marcos Llorente', 'DEF', 15, 'Atlético Madrid'],
    ['Rodri', 'MID', 8, 'Manchester City'], ['Pedri', 'MID', 16, 'Barcelona'], ['Gavi', 'MID', 9, 'Barcelona'],
    ['Fabián Ruiz', 'MID', 18, 'PSG'], ['Martín Zubimendi', 'MID', 6, 'Arsenal'], ['Mikel Merino', 'MID', 20, 'Arsenal'],
    ['Álex Baena', 'MID', 21, 'Atlético Madrid'],
    ['Lamine Yamal', 'FWD', 19, 'Barcelona'], ['Nico Williams', 'FWD', 17, 'Athletic Club'], ['Dani Olmo', 'FWD', 10, 'Barcelona'],
    ['Ferran Torres', 'FWD', 11, 'Barcelona'], ['Mikel Oyarzabal', 'FWD', 7, 'Real Sociedad'],
    ['Yéremy Pino', 'FWD', 22, 'Crystal Palace'], ['Borja Iglesias', 'FWD', 24, 'Celta de Vigo'],
  ]),
  s('URU', 'Uruguay', '🇺🇾', 'H', '4-3-3', 'Marcelo Bielsa', [
    ['Sergio Rochet', 'GK', 1, 'Internacional'], ['Fernando Muslera', 'GK', 12, 'Estudiantes'], ['Santiago Mele', 'GK', 23, 'Monterrey'],
    ['Ronald Araújo', 'DEF', 4, 'Barcelona'], ['José María Giménez', 'DEF', 2, 'Atlético Madrid'], ['Mathías Olivera', 'DEF', 16, 'Napoli'],
    ['Sebastián Cáceres', 'DEF', 3, 'Club America'], ['Santiago Bueno', 'DEF', 5, 'Wolves'],
    ['Joaquín Piquerez', 'DEF', 17, 'Palmeiras'], ['Guillermo Varela', 'DEF', 13, 'Flamengo'],
    ['Federico Valverde', 'MID', 15, 'Real Madrid'], ['Manuel Ugarte', 'MID', 5, 'Manchester United'],
    ['Rodrigo Bentancur', 'MID', 6, 'Tottenham'], ['Nicolás de la Cruz', 'MID', 7, 'Flamengo'],
    ['Giorgian de Arrascaeta', 'MID', 10, 'Fluminese'], ['Emiliano Martínez', 'MID', 8, 'Palmeiras'],
    ['Rodrigo Zalazar', 'MID', 20, 'Braga'], ['Facundo Pellistri', 'MID', 11, 'Panathinaikos'],
    ['Darwin Núñez', 'FWD', 9, 'Al Hilal'], ['Maximiliano Araújo', 'FWD', 13, 'Sporting CP'],
    ['Federico Viñas', 'FWD', 18, 'Real Oviedo'], ['Rodrigo Aguirre', 'FWD', 19, 'Tigres'],
  ]),

  // ═══ GROUP I ═══
  s('FRA', 'France', '🇫🇷', 'I', '4-3-3', 'Didier Deschamps', [
    ['Mike Maignan', 'GK', 16, 'AC Milan'], ['Brice Samba', 'GK', 1, 'Rennes'], ['Robin Risser', 'GK', 23, 'Lens'],
    ['William Saliba', 'DEF', 17, 'Arsenal'], ['Ibrahima Konaté', 'DEF', 24, 'Liverpool'], ['Dayot Upamecano', 'DEF', 2, 'Bayern Munich'],
    ['Jules Koundé', 'DEF', 5, 'Barcelona'], ['Théo Hernández', 'DEF', 22, 'Al-Hilal'], ['Lucas Hernández', 'DEF', 3, 'PSG'],
    ['Malo Gusto', 'DEF', 13, 'Chelsea'], ['Lucas Digne', 'DEF', 4, 'Aston Villa'],
    ['Aurélien Tchouaméni', 'MID', 8, 'Real Madrid'], ['N\'Golo Kanté', 'MID', 6, 'Fenerbahçe'],
    ['Adrien Rabiot', 'MID', 14, 'AC Milan'], ['Warren Zaïre-Emery', 'MID', 18, 'PSG'], ['Manu Koné', 'MID', 15, 'Roma'],
    ['Kylian Mbappé', 'FWD', 10, 'Real Madrid'], ['Ousmane Dembélé', 'FWD', 7, 'PSG'], ['Bradley Barcola', 'FWD', 20, 'PSG'],
    ['Marcus Thuram', 'FWD', 9, 'Inter Milan'], ['Michael Olise', 'FWD', 21, 'Bayern Munich'],
    ['Rayan Cherki', 'FWD', 12, 'Manchester City'], ['Désiré Doué', 'FWD', 11, 'PSG'],
    ['Jean-Philippe Mateta', 'FWD', 19, 'Crystal Palace'],
  ]),
  s('IRQ', 'Iraq', '🇮🇶', 'I', '4-4-2', 'Graham Arnold', [
    ['Jalal Hassan', 'GK', 1, 'Al-Zawraa'], ['Fahad Talib', 'GK', 12, 'Al-Talaba'], ['Ahmed Basil', 'GK', 22, 'Al-Shorta'],
    ['Hussein Ali', 'DEF', 2, 'Pogon Szczecin'], ['Rebin Sulaka', 'DEF', 4, 'Port'], ['Zaid Tahseen', 'DEF', 3, 'Pakhtakor'],
    ['Merchas Doski', 'DEF', 5, 'Viktoria Plzen'], ['Frans Putros', 'DEF', 6, 'Persib'], ['Mustafa Saadoon', 'DEF', 15, 'Al-Shorta'],
    ['Amir Al-Ammari', 'MID', 8, 'Cracovia'], ['Zidane Iqbal', 'MID', 10, 'Utrecht'], ['Ibrahim Bayesh', 'MID', 7, 'Al-Dhafra'],
    ['Youssef Amyn', 'MID', 14, 'AEK Larnaca'], ['Kevin Yakob', 'MID', 17, 'Aarhus GF'], ['Aimar Sher', 'MID', 18, 'Sarpsborg'],
    ['Ahmed Qasem', 'MID', 20, 'Nashville SC'],
    ['Aymen Hussein', 'FWD', 9, 'Al-Karma'], ['Ali Al-Hamadi', 'FWD', 11, 'Ipswich'], ['Ali Jassim', 'FWD', 7, 'Al-Najma'],
    ['Mohanad Ali', 'FWD', 19, 'Dibba'], ['Ali Yousef', 'FWD', 21, 'Al-Talaba'],
  ]),
  s('NOR', 'Norway', '🇳🇴', 'I', '4-3-3', 'Ståle Solbakken', [
    ['Orjan Nyland', 'GK', 1, 'Sevilla'], ['Egil Selvik', 'GK', 12, 'Watford'], ['Sander Tangvik', 'GK', 22, 'Hamburg SV'],
    ['Julian Ryerson', 'DEF', 14, 'Borussia Dortmund'], ['Kristoffer Ajer', 'DEF', 3, 'Brentford'], ['Leo Ostigård', 'DEF', 4, 'Genoa'],
    ['David Moller Wolfe', 'DEF', 19, 'Wolverhampton'], ['Marcus Pedersen', 'DEF', 2, 'Torino'],
    ['Torbjorn Heggem', 'DEF', 5, 'Bologna'],
    ['Martin Odegaard', 'MID', 10, 'Arsenal'], ['Sander Berge', 'MID', 8, 'Fulham'], ['Oscar Bobb', 'MID', 20, 'Fulham'],
    ['Kristian Thorstvedt', 'MID', 17, 'Sassuolo'], ['Patrick Berg', 'MID', 6, 'Bodo/Glimt'],
    ['Andreas Schjelderup', 'MID', 11, 'Benfica'], ['Antonio Nusa', 'MID', 7, 'RB Leipzig'], ['Fredrik Aursnes', 'MID', 18, 'Benfica'],
    ['Erling Haaland', 'FWD', 9, 'Manchester City'], ['Alexander Sorloth', 'FWD', 23, 'Atlético Madrid'],
    ['Jorgen Strand Larsen', 'FWD', 15, 'Crystal Palace'],
  ]),
  s('SEN', 'Senegal', '🇸🇳', 'I', '4-3-3', 'Pape Thiaw', [
    ['Edouard Mendy', 'GK', 16, 'Al-Ahli'], ['Mory Diaw', 'GK', 1, 'Le Havre'], ['Yehvann Diouf', 'GK', 23, 'Nice'],
    ['Kalidou Koulibaly', 'DEF', 3, 'Al-Hilal'], ['Moussa Niakhaté', 'DEF', 4, 'OL'], ['Abdoulaye Seck', 'DEF', 5, 'Maccabi Haifa'],
    ['Ismail Jakobs', 'DEF', 2, 'Galatasaray'], ['El Hadj Malick Diouf', 'DEF', 22, 'West Ham'],
    ['Mamadou Sarr', 'DEF', 6, 'Chelsea'], ['Krépin Diatta', 'DEF', 13, 'Monaco'],
    ['Pape Matar Sarr', 'MID', 17, 'Tottenham'], ['Lamine Camara', 'MID', 6, 'Monaco'],
    ['Idrissa Gana Gueye', 'MID', 5, 'Everton'], ['Habib Diarra', 'MID', 8, 'Sunderland'], ['Pathé Ciss', 'MID', 15, 'Rayo Vallecano'],
    ['Sadio Mané', 'FWD', 10, 'Al-Nassr'], ['Ismaila Sarr', 'FWD', 18, 'Crystal Palace'], ['Nicolas Jackson', 'FWD', 7, 'Bayern Munich'],
    ['Iliman Ndiaye', 'FWD', 11, 'Everton'], ['Assane Diao', 'FWD', 9, 'Como'], ['Cherif Ndiaye', 'FWD', 14, 'Samsunspor'],
    ['Bamba Dieng', 'FWD', 20, 'Lorient'],
  ]),

  // ═══ GROUP J ═══
  s('ALG', 'Algeria', '🇩🇿', 'J', '4-3-3', 'Vladimir Petković', [
    ['Luca Zidane', 'GK', 23, 'Granada'], ['Oussama Benbot', 'GK', 1, 'USM Alger'], ['Melvin Mastil', 'GK', 16, 'Stade Nyonnais'],
    ['Ramy Bensebaini', 'DEF', 2, 'Borussia Dortmund'], ['Rayan Aït-Nouri', 'DEF', 3, 'Manchester City'],
    ['Aïssa Mandi', 'DEF', 5, 'Lille'], ['Jaouen Hadjam', 'DEF', 13, 'Young Boys'], ['Rafik Belghali', 'DEF', 6, 'Hellas Verona'],
    ['Zineddine Belaïd', 'DEF', 4, 'JS Kabylie'], ['Mohamed Amine Tougaï', 'DEF', 15, 'Espérance de Tunis'],
    ['Houssem Aouar', 'MID', 6, 'Al-Ittihad'], ['Nabil Bentaleb', 'MID', 8, 'Lille'], ['Hicham Boudaoui', 'MID', 14, 'Nice'],
    ['Farès Chaïbi', 'MID', 7, 'Eintracht Frankfurt'], ['Ibrahim Maza', 'MID', 10, 'Bayer Leverkusen'],
    ['Ramiz Zerrouki', 'MID', 17, 'FC Twente'],
    ['Riyad Mahrez', 'FWD', 7, 'Al-Ahli'], ['Mohamed Amine Amoura', 'FWD', 9, 'Wolfsburg'],
    ['Amine Gouiri', 'FWD', 11, 'Marseille'], ['Anis Hadj Moussa', 'FWD', 19, 'Feyenoord'],
    ['Adil Boulbina', 'FWD', 21, 'Al-Duhail'], ['Farès Ghedjemis', 'FWD', 22, 'Frosinone'],
  ]),
  s('ARG', 'Argentina', '🇦🇷', 'J', '4-3-3', 'Lionel Scaloni', [
    ['Emiliano Martínez', 'GK', 23, 'Aston Villa'], ['Gerónimo Rulli', 'GK', 12, 'Marseille'], ['Juan Musso', 'GK', 1, 'Atletico Madrid'],
    ['Cristian Romero', 'DEF', 13, 'Tottenham'], ['Lisandro Martínez', 'DEF', 25, 'Manchester United'],
    ['Nicolás Otamendi', 'DEF', 19, 'Benfica'], ['Nahuel Molina', 'DEF', 26, 'Atletico Madrid'],
    ['Leonardo Balerdi', 'DEF', 6, 'Marseille'], ['Nicolás Tagliafico', 'DEF', 8, 'Lyon'],
    ['Gonzalo Montiel', 'DEF', 4, 'River Plate'], ['Facundo Medina', 'DEF', 2, 'Marseille'],
    ['Alexis Mac Allister', 'MID', 20, 'Liverpool'], ['Enzo Fernández', 'MID', 24, 'Chelsea'],
    ['Rodrigo De Paul', 'MID', 7, 'Inter Miami'], ['Leandro Paredes', 'MID', 5, 'Boca Juniors'],
    ['Giovani Lo Celso', 'MID', 16, 'Real Betis'], ['Exequiel Palacios', 'MID', 14, 'Bayer Leverkusen'],
    ['Lionel Messi', 'FWD', 10, 'Inter Miami'], ['Julián Álvarez', 'FWD', 9, 'Atletico Madrid'],
    ['Lautaro Martínez', 'FWD', 22, 'Internazionale'], ['Nicolás González', 'FWD', 15, 'Atletico Madrid'],
    ['Thiago Almada', 'FWD', 11, 'Atletico Madrid'], ['Giuliano Simeone', 'FWD', 17, 'Atletico Madrid'],
    ['Nicolás Paz', 'FWD', 21, 'Como 1907'],
  ]),
  s('AUT', 'Austria', '🇦🇹', 'J', '4-4-2', 'Ralf Rangnick', [
    ['Patrick Pentz', 'GK', 1, 'Brondby'], ['Alexander Schlager', 'GK', 13, 'RB Salzburg'], ['Florian Wiegele', 'GK', 22, 'Viktoria Pilsen'],
    ['David Alaba', 'DEF', 8, 'Real Madrid'], ['Kevin Danso', 'DEF', 4, 'Tottenham'], ['Philipp Lienhart', 'DEF', 15, 'Freiburg'],
    ['Stefan Posch', 'DEF', 5, 'Mainz'], ['Phillipp Mwene', 'DEF', 2, 'Mainz'], ['Alexander Prass', 'DEF', 3, 'Hoffenheim'],
    ['Marco Friedl', 'DEF', 6, 'Werder Bremen'],
    ['Konrad Laimer', 'MID', 20, 'Bayern Munich'], ['Marcel Sabitzer', 'MID', 9, 'Borussia Dortmund'],
    ['Christoph Baumgartner', 'MID', 19, 'RB Leipzig'], ['Nicolas Seiwald', 'MID', 6, 'RB Leipzig'],
    ['Xaver Schlager', 'MID', 17, 'RB Leipzig'], ['Romano Schmid', 'MID', 10, 'Werder Bremen'],
    ['Patrick Wimmer', 'MID', 14, 'Wolfsburg'], ['Paul Wanner', 'MID', 18, 'PSV Eindhoven'],
    ['Marko Arnautović', 'FWD', 7, 'Red Star Belgrade'], ['Michael Gregoritsch', 'FWD', 11, 'Augsburg'],
    ['Saša Kalajdžić', 'FWD', 21, 'LASK'],
  ]),
  s('JOR', 'Jordan', '🇯🇴', 'J', '4-4-2', 'Jamal Sellami', [
    ['Yazeed Abulaila', 'GK', 1, 'Al-Hussein'], ['Abdullah Al-Fakhouri', 'GK', 12, 'Al-Wehdat'], ['Noor Bani Attiah', 'GK', 22, 'Al-Faisaly'],
    ['Abdallah Nasib', 'DEF', 4, 'Al-Zawraa'], ['Yazan Al-Arab', 'DEF', 5, 'FC Seoul'], ['Ehsan Haddad', 'DEF', 2, 'Al-Hussein'],
    ['Mohammad Abualnadi', 'DEF', 3, 'Selangor'], ['Mohammad Abu Hasheesh', 'DEF', 13, 'Al-Karma'],
    ['Nizar Al-Rashdan', 'MID', 8, 'Qatar'], ['Noor Al-Rawabdeh', 'MID', 6, 'Selangor'], ['Ibrahim Saadeh', 'MID', 10, 'Al-Karma'],
    ['Rajaei Ayed', 'MID', 14, 'Al-Hussein'], ['Mahmoud Al-Mardi', 'MID', 17, 'Al-Hussein'],
    ['Mousa Al-Tamari', 'FWD', 11, 'Rennes'], ['Odeh Al-Fakhouri', 'FWD', 9, 'Pyramids'],
    ['Ali Olwan', 'FWD', 7, 'Al-Sailiya'], ['Mohammad Abu Zrayq', 'FWD', 18, 'Raja Casablanca'],
    ['Ali Azaizeh', 'FWD', 20, 'Al-Shabab'],
  ]),

  // ═══ GROUP K ═══
  s('COL', 'Colombia', '🇨🇴', 'K', '4-2-3-1', 'Nestor Lorenzo', [
    ['Camilo Vargas', 'GK', 12, 'Atlas'], ['David Ospina', 'GK', 1, 'Atlético Nacional'], ['Álvaro Montero', 'GK', 22, 'Vélez Sarsfield'],
    ['Davinson Sánchez', 'DEF', 23, 'Galatasaray'], ['Yerry Mina', 'DEF', 2, 'Cagliari'], ['Jhon Lucumí', 'DEF', 3, 'Bologna'],
    ['Daniel Muñoz', 'DEF', 21, 'Crystal Palace'], ['Johan Mojica', 'DEF', 17, 'Mallorca'], ['Santiago Arias', 'DEF', 4, 'Independiente'],
    ['Deiver Machado', 'DEF', 6, 'Nantes'],
    ['Jefferson Lerma', 'MID', 16, 'Crystal Palace'], ['Richard Ríos', 'MID', 8, 'Benfica'], ['James Rodríguez', 'MID', 10, 'Minnesota United'],
    ['Juan Fernando Quintero', 'MID', 20, 'River Plate'], ['Jhon Arias', 'MID', 11, 'Palmeiras'],
    ['Jorge Carrascal', 'MID', 15, 'Flamengo'], ['Kevin Castaño', 'MID', 14, 'Racing'],
    ['Luis Díaz', 'FWD', 7, 'Bayern Munich'], ['Luis Suárez', 'FWD', 9, 'Sporting'], ['Jhon Córdoba', 'FWD', 19, 'Krasnodar'],
    ['Juan Camilo Hernández', 'FWD', 18, 'Betis'],
  ]),
  s('COD', 'DR Congo', '🇨🇩', 'K', '4-4-2', 'Sébastien Desabre', [
    ['Lionel Mpasi', 'GK', 1, 'Le Havre'], ['Timothy Fayulu', 'GK', 12, 'Noah'], ['Matthieu Epolo', 'GK', 22, 'Standard Liege'],
    ['Chancel Mbemba', 'DEF', 5, 'Lille'], ['Axel Tuanzebe', 'DEF', 2, 'Burnley'], ['Aaron Wan-Bissaka', 'DEF', 3, 'West Ham United'],
    ['Arthur Masuaku', 'DEF', 15, 'Lens'], ['Joris Kayembe', 'DEF', 13, 'Racing Genk'], ['Dylan Batubinsika', 'DEF', 4, 'Larisa'],
    ['Théo Bongonda', 'MID', 7, 'Spartak Moscow'], ['Gaël Kakuta', 'MID', 10, 'Larisa'], ['Edo Kayembe', 'MID', 8, 'Watford'],
    ['Ngal\'ayel Mukau', 'MID', 17, 'Lille'], ['Charles Pickel', 'MID', 18, 'Espanyol'], ['Samuel Moutossamy', 'MID', 14, 'Atromitos'],
    ['Noah Sadiki', 'MID', 20, 'Sunderland'],
    ['Yoane Wissa', 'FWD', 9, 'Newcastle United'], ['Cédric Bakambu', 'FWD', 11, 'Real Betis'],
    ['Simon Banza', 'FWD', 19, 'Al Jazira'], ['Fiston Mayele', 'FWD', 21, 'Pyramids'],
  ]),
  s('POR', 'Portugal', '🇵🇹', 'K', '4-3-3', 'Roberto Martínez', [
    ['Diogo Costa', 'GK', 22, 'Porto'], ['José Sá', 'GK', 1, 'Wolverhampton'], ['Rui Silva', 'GK', 12, 'Sporting Lisbon'],
    ['Rúben Dias', 'DEF', 3, 'Manchester City'], ['João Cancelo', 'DEF', 20, 'Barcelona'], ['Nuno Mendes', 'DEF', 19, 'PSG'],
    ['Diogo Dalot', 'DEF', 2, 'Manchester United'], ['Gonçalo Inácio', 'DEF', 14, 'Sporting Lisbon'],
    ['Renato Veiga', 'DEF', 5, 'Villarreal'], ['Tomás Araújo', 'DEF', 4, 'Benfica'], ['Nélson Semedo', 'DEF', 13, 'Fenerbahçe'],
    ['Bruno Fernandes', 'MID', 8, 'Manchester United'], ['Bernardo Silva', 'MID', 10, 'Manchester City'],
    ['Vitinha', 'MID', 23, 'PSG'], ['João Neves', 'MID', 21, 'PSG'], ['Rúben Neves', 'MID', 6, 'Al Hilal'],
    ['Matheus Nunes', 'MID', 15, 'Manchester City'],
    ['Cristiano Ronaldo', 'FWD', 7, 'Al Nassr'], ['Rafael Leão', 'FWD', 17, 'AC Milan'], ['Pedro Neto', 'FWD', 11, 'Chelsea'],
    ['Gonçalo Ramos', 'FWD', 26, 'PSG'], ['João Félix', 'FWD', 9, 'Al Nassr'], ['Francisco Conceição', 'FWD', 18, 'Juventus'],
    ['Francisco Trincão', 'FWD', 16, 'Sporting Lisbon'],
  ]),
  s('UZB', 'Uzbekistan', '🇺🇿', 'K', '4-4-2', 'Fabio Cannavaro', [
    ['Utkir Yusupov', 'GK', 1, 'Navbahor'], ['Abduvohid Nematov', 'GK', 12, 'Nasaf'], ['Botirali Ergashev', 'GK', 22, 'Neftchi'],
    ['Abdukodir Khusanov', 'DEF', 5, 'Manchester City'], ['Rustam Ashurmatov', 'DEF', 4, 'Esteghlal'],
    ['Khojiakbar Alijonov', 'DEF', 3, 'Pakhtakor'], ['Farrukh Sayfiev', 'DEF', 2, 'Neftchi'],
    ['Umar Eshmurodov', 'DEF', 15, 'Nasaf'], ['Sherzod Nasrullaev', 'DEF', 13, 'Nasaf'],
    ['Otabek Shukurov', 'MID', 8, 'Baniyas'], ['Jaloliddin Masharipov', 'MID', 10, 'Esteghlal'],
    ['Odiljon Hamrobekov', 'MID', 6, 'Tractor'], ['Oston Urunov', 'MID', 17, 'Persepolis'],
    ['Abbosbek Fayzullaev', 'MID', 7, 'Istanbul Basaksehir'], ['Jamshid Iskanderov', 'MID', 14, 'Neftchi'],
    ['Eldor Shomurodov', 'FWD', 9, 'Istanbul Basaksehir'], ['Igor Sergeev', 'FWD', 11, 'Persepolis'],
    ['Azizbek Amonov', 'FWD', 19, 'Bukhara'],
  ]),

  // ═══ GROUP L ═══
  s('CRO', 'Croatia', '🇭🇷', 'L', '4-3-3', 'Zlatko Dalić', [
    ['Dominik Livaković', 'GK', 1, 'Dinamo Zagreb'], ['Dominik Kotarski', 'GK', 12, 'FC Copenhagen'], ['Ivor Pandur', 'GK', 23, 'Hull City'],
    ['Joško Gvardiol', 'DEF', 4, 'Manchester City'], ['Josip Šutalo', 'DEF', 6, 'Ajax'], ['Josip Stanišić', 'DEF', 2, 'Bayern Munich'],
    ['Duje Ćaleta-Car', 'DEF', 5, 'Real Sociedad'], ['Marin Pongračić', 'DEF', 3, 'Fiorentina'],
    ['Martin Erlić', 'DEF', 15, 'Midtjylland'], ['Luka Vušković', 'DEF', 13, 'Hamburger SV'],
    ['Luka Modrić', 'MID', 10, 'AC Milan'], ['Mateo Kovačić', 'MID', 8, 'Manchester City'], ['Mario Pašalić', 'MID', 15, 'Atalanta'],
    ['Nikola Vlašić', 'MID', 7, 'Torino'], ['Luka Sučić', 'MID', 25, 'Real Sociedad'], ['Martin Baturina', 'MID', 17, 'Como'],
    ['Petar Sučić', 'MID', 20, 'Inter'], ['Kristijan Jakić', 'MID', 14, 'Augsburg'],
    ['Andrej Kramarić', 'FWD', 9, 'Hoffenheim'], ['Ante Budimir', 'FWD', 17, 'Osasuna'], ['Ivan Perišić', 'FWD', 14, 'PSV Eindhoven'],
    ['Petar Musa', 'FWD', 11, 'FC Dallas'], ['Igor Matanović', 'FWD', 19, 'Freiburg'],
  ]),
  s('ENG', 'England', '🏴󠁧󠁢󠁥󠁮󠁧󠁿', 'L', '4-2-3-1', 'Thomas Tuchel', [
    ['Jordan Pickford', 'GK', 1, 'Everton'], ['Dean Henderson', 'GK', 23, 'Crystal Palace'], ['James Trafford', 'GK', 13, 'Manchester City'],
    ['John Stones', 'DEF', 5, 'Manchester City'], ['Marc Guéhi', 'DEF', 6, 'Manchester City'], ['Reece James', 'DEF', 2, 'Chelsea'],
    ['Ezri Konsa', 'DEF', 15, 'Aston Villa'], ['Tino Livramento', 'DEF', 3, 'Newcastle'],
    ['Jarell Quansah', 'DEF', 4, 'Bayer Leverkusen'], ['Djed Spence', 'DEF', 22, 'Tottenham'], ['Dan Burn', 'DEF', 12, 'Newcastle'],
    ['Jude Bellingham', 'MID', 10, 'Real Madrid'], ['Declan Rice', 'MID', 4, 'Arsenal'], ['Kobbie Mainoo', 'MID', 8, 'Manchester United'],
    ['Morgan Rogers', 'MID', 16, 'Aston Villa'], ['Elliot Anderson', 'MID', 14, 'Nottingham Forest'],
    ['Eberechi Eze', 'MID', 20, 'Arsenal'], ['Jordan Henderson', 'MID', 18, 'Brentford'],
    ['Harry Kane', 'FWD', 9, 'Bayern Munich'], ['Bukayo Saka', 'FWD', 7, 'Arsenal'], ['Marcus Rashford', 'FWD', 11, 'Barcelona'],
    ['Anthony Gordon', 'FWD', 19, 'Newcastle'], ['Ollie Watkins', 'FWD', 17, 'Aston Villa'], ['Ivan Toney', 'FWD', 21, 'Al-Ahli'],
  ]),
  s('GHA', 'Ghana', '🇬🇭', 'L', '4-4-2', 'Carlos Queiroz', [
    ['Lawrence Ati-Zigi', 'GK', 1, 'St. Gallen'], ['Benjamin Asare', 'GK', 12, 'Accra Hearts of Oak'], ['Joseph Anang', 'GK', 16, 'St. Patrick\'s Athletic'],
    ['Alidu Seidu', 'DEF', 2, 'Rennes'], ['Abdul Mumin', 'DEF', 4, 'Rayo Vallecano'], ['Jerome Opoku', 'DEF', 5, 'Istanbul Basaksehir'],
    ['Gideon Mensah', 'DEF', 3, 'Auxerre'], ['Baba Rahman', 'DEF', 17, 'PAOK'], ['Jonas Adjetey', 'DEF', 15, 'Wolfsburg'],
    ['Marvin Senaya', 'DEF', 13, 'Auxerre'],
    ['Thomas Partey', 'MID', 8, 'Villarreal'], ['Elisha Owusu', 'MID', 6, 'Auxerre'], ['Kwasi Sibo', 'MID', 14, 'Real Oviedo'],
    ['Abdul Fatawu Issahaku', 'MID', 7, 'Leicester City'], ['Augustine Boakye', 'MID', 18, 'Saint-Etienne'],
    ['Inaki Williams', 'FWD', 9, 'Athletic Bilbao'], ['Antoine Semenyo', 'FWD', 10, 'Manchester City'],
    ['Kamaldeen Sulemana', 'FWD', 11, 'Atlanta'], ['Ernest Nuamah', 'FWD', 19, 'Lyon'],
    ['Jordan Ayew', 'FWD', 20, 'Leicester City'], ['Brandon Thomas-Asante', 'FWD', 21, 'Coventry City'],
  ]),
  s('PAN', 'Panama', '🇵🇦', 'L', '4-4-2', 'Thomas Christiansen', [
    ['Orlando Mosquera', 'GK', 1, 'Al Fayha'], ['Luis Mejía', 'GK', 12, 'Nacional'], ['César Samudio', 'GK', 22, 'Marathón'],
    ['Fidel Escobar', 'DEF', 4, 'Saprissa'], ['Amir Murillo', 'DEF', 23, 'Beşiktaş'], ['José Córdoba', 'DEF', 3, 'Norwich City'],
    ['César Blackman', 'DEF', 2, 'Slovan Bratislava'], ['Andrés Andrade', 'DEF', 5, 'LASK'],
    ['Edgardo Fariña', 'DEF', 15, 'Pari Nizhny Novgorod'], ['Éric Davis', 'DEF', 13, 'Plaza Amador'],
    ['Adalberto Carrasquilla', 'MID', 8, 'Pumas UNAM'], ['Aníbal Godoy', 'MID', 20, 'San Diego FC'],
    ['Carlos Harvey', 'MID', 14, 'Minnesota United'], ['José Luis Rodríguez', 'MID', 7, 'Juárez'],
    ['Yoel Bárcenas', 'MID', 10, 'Mazatlán'], ['Cristian Martínez', 'MID', 18, 'Ironi Kiryat Shmona'],
    ['Ismael Díaz', 'FWD', 11, 'León'], ['José Fajardo', 'FWD', 9, 'Universidad Católica'],
    ['Cecilio Waterman', 'FWD', 19, 'Universidad de Concepción'], ['Tomás Rodríguez', 'FWD', 17, 'Saprissa'],
  ]),
];

export default squads;
